begin
  require "bundler/gem_tasks"
rescue LoadError
  # Bundler is optional for running tests
end
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
end

task :default => :test
