package Image::LibSIXEL::Constants;
use strict;
use warnings;

use Exporter 'import';

our @EXPORT_OK = qw(
    SIXEL_INTERNAL_API
    LIBSIXEL_VERSION
    LIBSIXEL_ABI_VERSION
    SIXEL_OUTPUT_PACKET_SIZE
    SIXEL_PALETTE_MIN
    SIXEL_PALETTE_MAX
    SIXEL_USE_DEPRECATED_SYMBOLS
    SIXEL_ALLOCATE_BYTES_MAX
    SIXEL_WIDTH_LIMIT
    SIXEL_HEIGHT_LIMIT
    SIXEL_DEFALUT_GIF_DELAY
    SIXEL_OK
    SIXEL_FALSE
    SIXEL_RUNTIME_ERROR
    SIXEL_LOGIC_ERROR
    SIXEL_FEATURE_ERROR
    SIXEL_LIBC_ERROR
    SIXEL_CURL_ERROR
    SIXEL_JPEG_ERROR
    SIXEL_PNG_ERROR
    SIXEL_WEBP_ERROR
    SIXEL_TIFF_ERROR
    SIXEL_GDK_ERROR
    SIXEL_GD_ERROR
    SIXEL_STBI_ERROR
    SIXEL_STBIW_ERROR
    SIXEL_COM_ERROR
    SIXEL_WIC_ERROR
    SIXEL_INTERRUPTED
    SIXEL_BAD_ALLOCATION
    SIXEL_BAD_ARGUMENT
    SIXEL_BAD_INPUT
    SIXEL_BAD_INTEGER_OVERFLOW
    SIXEL_BAD_FILE_PATH
    SIXEL_BAD_CLIPBOARD
    SIXEL_LOADER_FAILED
    SIXEL_NOT_IMPLEMENTED
    SIXEL_LARGE_AUTO
    SIXEL_LARGE_NORM
    SIXEL_LARGE_LUM
    SIXEL_LARGE_PCA
    SIXEL_REP_AUTO
    SIXEL_REP_CENTER_BOX
    SIXEL_REP_AVERAGE_COLORS
    SIXEL_REP_AVERAGE_PIXELS
    SIXEL_DIFFUSE_AUTO
    SIXEL_DIFFUSE_NONE
    SIXEL_DIFFUSE_ATKINSON
    SIXEL_DIFFUSE_FS
    SIXEL_DIFFUSE_JAJUNI
    SIXEL_DIFFUSE_STUCKI
    SIXEL_DIFFUSE_BURKES
    SIXEL_DIFFUSE_A_DITHER
    SIXEL_DIFFUSE_X_DITHER
    SIXEL_DIFFUSE_BLUENOISE_DITHER
    SIXEL_DIFFUSE_LSO2
    SIXEL_DIFFUSE_INTERFRAME
    SIXEL_DIFFUSE_SIERRA1
    SIXEL_DIFFUSE_SIERRA2
    SIXEL_DIFFUSE_SIERRA3
    SIXEL_SCAN_AUTO
    SIXEL_SCAN_RASTER
    SIXEL_SCAN_SERPENTINE
    SIXEL_QUALITY_AUTO
    SIXEL_QUALITY_HIGH
    SIXEL_QUALITY_LOW
    SIXEL_QUALITY_FULL
    SIXEL_QUALITY_HIGHCOLOR
    SIXEL_LUT_POLICY_AUTO
    SIXEL_LUT_POLICY_5BIT
    SIXEL_LUT_POLICY_6BIT
    SIXEL_LUT_POLICY_NONE
    SIXEL_LUT_POLICY_CERTLUT
    SIXEL_LUT_POLICY_FHEDT
    SIXEL_LUT_POLICY_EYTZINGER
    SIXEL_LUT_POLICY_VPTREE
    SIXEL_LUT_POLICY_RBC
    SIXEL_LUT_POLICY_MAHALANOBIS
    SIXEL_BUILTIN_MONO_DARK
    SIXEL_BUILTIN_MONO_LIGHT
    SIXEL_BUILTIN_XTERM16
    SIXEL_BUILTIN_XTERM256
    SIXEL_BUILTIN_VT340_MONO
    SIXEL_BUILTIN_VT340_COLOR
    SIXEL_BUILTIN_G1
    SIXEL_BUILTIN_G2
    SIXEL_BUILTIN_G4
    SIXEL_BUILTIN_G8
    SIXEL_COLORSPACE_GAMMA
    SIXEL_COLORSPACE_LINEAR
    SIXEL_COLORSPACE_OKLAB
    SIXEL_COLORSPACE_SMPTEC
    SIXEL_COLORSPACE_CIELAB
    SIXEL_COLORSPACE_DIN99D
    SIXEL_FORMATTYPE_COLOR
    SIXEL_FORMATTYPE_GRAYSCALE
    SIXEL_FORMATTYPE_PALETTE
    SIXEL_DEQUANTIZE_NONE
    SIXEL_DEQUANTIZE_K_UNDITHER
    SIXEL_DEQUANTIZE_LSO_UNDITHER_VFS
    SIXEL_DEQUANTIZE_LSO_UNDITHER_VLIGHT
    SIXEL_QUANTIZE_MODEL_AUTO
    SIXEL_QUANTIZE_MODEL_MEDIANCUT
    SIXEL_QUANTIZE_MODEL_KMEANS
    SIXEL_QUANTIZE_MODEL_KMEDOIDS
    SIXEL_QUANTIZE_MODEL_KCENTER
    SIXEL_QUANTIZE_MODEL_STICKY
    SIXEL_FINAL_MERGE_AUTO
    SIXEL_FINAL_MERGE_NONE
    SIXEL_FINAL_MERGE_WARD
    SIXEL_PIXELFORMAT_RGB555
    SIXEL_PIXELFORMAT_RGB565
    SIXEL_PIXELFORMAT_RGB888
    SIXEL_PIXELFORMAT_BGR555
    SIXEL_PIXELFORMAT_BGR565
    SIXEL_PIXELFORMAT_BGR888
    SIXEL_PIXELFORMAT_ARGB8888
    SIXEL_PIXELFORMAT_RGBA8888
    SIXEL_PIXELFORMAT_ABGR8888
    SIXEL_PIXELFORMAT_BGRA8888
    SIXEL_PIXELFORMAT_RGBFLOAT32
    SIXEL_PIXELFORMAT_LINEARRGBFLOAT32
    SIXEL_PIXELFORMAT_OKLABFLOAT32
    SIXEL_PIXELFORMAT_CIELABFLOAT32
    SIXEL_PIXELFORMAT_DIN99DFLOAT32
    SIXEL_PIXELFORMAT_G1
    SIXEL_PIXELFORMAT_G2
    SIXEL_PIXELFORMAT_G4
    SIXEL_PIXELFORMAT_G8
    SIXEL_PIXELFORMAT_AG88
    SIXEL_PIXELFORMAT_GA88
    SIXEL_PIXELFORMAT_PAL1
    SIXEL_PIXELFORMAT_PAL2
    SIXEL_PIXELFORMAT_PAL4
    SIXEL_PIXELFORMAT_PAL8
    SIXEL_PALETTETYPE_AUTO
    SIXEL_PALETTETYPE_HLS
    SIXEL_PALETTETYPE_RGB
    SIXEL_ENCODEPOLICY_AUTO
    SIXEL_ENCODEPOLICY_FAST
    SIXEL_ENCODEPOLICY_SIZE
    SIXEL_RES_NEAREST
    SIXEL_RES_GAUSSIAN
    SIXEL_RES_HANNING
    SIXEL_RES_HAMMING
    SIXEL_RES_BILINEAR
    SIXEL_RES_WELSH
    SIXEL_RES_BICUBIC
    SIXEL_RES_LANCZOS2
    SIXEL_RES_LANCZOS3
    SIXEL_RES_LANCZOS4
    SIXEL_FORMAT_GIF
    SIXEL_FORMAT_PNG
    SIXEL_FORMAT_BMP
    SIXEL_FORMAT_JPG
    SIXEL_FORMAT_TGA
    SIXEL_FORMAT_WBMP
    SIXEL_FORMAT_TIFF
    SIXEL_FORMAT_SIXEL
    SIXEL_FORMAT_PNM
    SIXEL_FORMAT_GD2
    SIXEL_FORMAT_PSD
    SIXEL_FORMAT_HDR
    SIXEL_LOOP_AUTO
    SIXEL_LOOP_FORCE
    SIXEL_LOOP_DISABLE
    SIXEL_TRANSPARENT_POLICY_COMPOSITE
    SIXEL_TRANSPARENT_POLICY_BACKGROUND
    SIXEL_TRANSPARENT_POLICY_KEEP
    SIXEL_TRANSPARENT_POLICY_P2_0
    SIXEL_TRANSPARENT_POLICY_P2_1
    SIXEL_6DELTA_ERROR_DIFFUSE
    SIXEL_6DELTA_ERROR_SKIP
    SIXEL_OPTFLAG_INPUT
    SIXEL_OPTFLAG_OUTPUT
    SIXEL_OPTFLAG_DEQUANTIZE
    SIXEL_OPTFLAG_DIRECT
    SIXEL_OPTFLAG_SIMILARITY
    SIXEL_OPTFLAG_SIZE
    SIXEL_OPTFLAG_EDGE
    SIXEL_OPTFLAG_OUTFILE
    SIXEL_OPTFLAG_7BIT_MODE
    SIXEL_OPTFLAG_8BIT_MODE
    SIXEL_OPTFLAG_6REVERSIBLE
    SIXEL_OPTFLAG_HAS_GRI_ARG_LIMIT
    SIXEL_OPTFLAG_PRECISION
    SIXEL_OPTFLAG_THREADS
    SIXEL_OPTFLAG_COLORS
    SIXEL_OPTFLAG_MAPFILE
    SIXEL_OPTFLAG_MAPFILE_OUTPUT
    SIXEL_OPTFLAG_MONOCHROME
    SIXEL_OPTFLAG_INSECURE
    SIXEL_OPTFLAG_INVERT
    SIXEL_OPTFLAG_HIGH_COLOR
    SIXEL_OPTFLAG_USE_MACRO
    SIXEL_OPTFLAG_MACRO_NUMBER
    SIXEL_OPTFLAG_COMPLEXION_SCORE
    SIXEL_OPTFLAG_IGNORE_DELAY
    SIXEL_OPTFLAG_STATIC
    SIXEL_OPTFLAG_DIFFUSION
    SIXEL_OPTFLAG_FIND_LARGEST
    SIXEL_OPTFLAG_SELECT_COLOR
    SIXEL_OPTFLAG_QUANTIZE_MODEL
    SIXEL_OPTFLAG_CROP
    SIXEL_OPTFLAG_WIDTH
    SIXEL_OPTFLAG_HEIGHT
    SIXEL_OPTFLAG_RESAMPLING
    SIXEL_OPTFLAG_QUALITY
    SIXEL_OPTFLAG_LOOPMODE
    SIXEL_OPTFLAG_START_FRAME
    SIXEL_OPTFLAG_PALETTE_TYPE
    SIXEL_OPTFLAG_BUILTIN_PALETTE
    SIXEL_OPTFLAG_ENCODE_POLICY
    SIXEL_OPTFLAG_LUT_POLICY
    SIXEL_OPTFLAG_CLUSTERING_COLORSPACE
    SIXEL_OPTFLAG_WORKING_COLORSPACE
    SIXEL_OPTFLAG_OUTPUT_COLORSPACE
    SIXEL_OPTFLAG_ORMODE
    SIXEL_OPTFLAG_TRANSPARENT_POLICY
    SIXEL_OPTFLAG_TRANSPARENT_OFFSET
    SIXEL_OPTFLAG_6DELTA_THRESHOLD
    SIXEL_OPTFLAG_6DELTA_ERROR
    SIXEL_OPTFLAG_BGCOLOR
    SIXEL_OPTFLAG_PENETRATE
    SIXEL_OPTFLAG_DRCS
    SIXEL_OPTFLAG_PIPE_MODE
    SIXEL_OPTFLAG_VERBOSE
    SIXEL_OPTFLAG_LOADERS
    SIXEL_OPTFLAG_VERSION
    SIXEL_OPTFLAG_HELP
    SIXEL_LOADER_OPTION_REQUIRE_STATIC
    SIXEL_LOADER_OPTION_USE_PALETTE
    SIXEL_LOADER_OPTION_REQCOLORS
    SIXEL_LOADER_OPTION_BGCOLOR
    SIXEL_LOADER_OPTION_LOOP_CONTROL
    SIXEL_LOADER_OPTION_INSECURE
    SIXEL_LOADER_OPTION_CANCEL_FLAG
    SIXEL_LOADER_OPTION_LOADER_ORDER
    SIXEL_LOADER_OPTION_CONTEXT
    SIXEL_LOADER_OPTION_WIC_ICO_MINSIZE
    SIXEL_LOADER_OPTION_START_FRAME_NO
    SIXEL_LOADER_OPTION_BGCOLOR_SOURCE
    SIXEL_LOADER_BGCOLOR_SOURCE_EXPLICIT
    SIXEL_LOADER_BGCOLOR_SOURCE_ENV
);

# Auto-generated from include/sixel.h.in. Do not edit manually.
use constant {
    SIXEL_INTERNAL_API => 'SIXELAPI',
    LIBSIXEL_VERSION => '@PACKAGE_VERSION@',
    LIBSIXEL_ABI_VERSION => '@LS_LTVERSION@',
    SIXEL_OUTPUT_PACKET_SIZE => 16384,
    SIXEL_PALETTE_MIN => 2,
    SIXEL_PALETTE_MAX => 256,
    SIXEL_USE_DEPRECATED_SYMBOLS => 1,
    SIXEL_ALLOCATE_BYTES_MAX => 134217728,
    SIXEL_WIDTH_LIMIT => 1000000,
    SIXEL_HEIGHT_LIMIT => 1000000,
    SIXEL_DEFALUT_GIF_DELAY => 1,
    SIXEL_OK => 0,
    SIXEL_FALSE => 4096,
    SIXEL_RUNTIME_ERROR => 4352,
    SIXEL_LOGIC_ERROR => 4608,
    SIXEL_FEATURE_ERROR => 4864,
    SIXEL_LIBC_ERROR => 5120,
    SIXEL_CURL_ERROR => 5376,
    SIXEL_JPEG_ERROR => 5632,
    SIXEL_PNG_ERROR => 5888,
    SIXEL_WEBP_ERROR => 5968,
    SIXEL_TIFF_ERROR => 5984,
    SIXEL_GDK_ERROR => 6144,
    SIXEL_GD_ERROR => 6400,
    SIXEL_STBI_ERROR => 6656,
    SIXEL_STBIW_ERROR => 6912,
    SIXEL_COM_ERROR => 7168,
    SIXEL_WIC_ERROR => 7424,
    SIXEL_INTERRUPTED => 1,
    SIXEL_BAD_ALLOCATION => 4353,
    SIXEL_BAD_ARGUMENT => 4354,
    SIXEL_BAD_INPUT => 4355,
    SIXEL_BAD_INTEGER_OVERFLOW => 4356,
    SIXEL_BAD_FILE_PATH => 4357,
    SIXEL_BAD_CLIPBOARD => 4358,
    SIXEL_LOADER_FAILED => 4359,
    SIXEL_NOT_IMPLEMENTED => 4865,
    SIXEL_LARGE_AUTO => 0,
    SIXEL_LARGE_NORM => 1,
    SIXEL_LARGE_LUM => 2,
    SIXEL_LARGE_PCA => 3,
    SIXEL_REP_AUTO => 0,
    SIXEL_REP_CENTER_BOX => 1,
    SIXEL_REP_AVERAGE_COLORS => 2,
    SIXEL_REP_AVERAGE_PIXELS => 3,
    SIXEL_DIFFUSE_AUTO => 0,
    SIXEL_DIFFUSE_NONE => 1,
    SIXEL_DIFFUSE_ATKINSON => 2,
    SIXEL_DIFFUSE_FS => 3,
    SIXEL_DIFFUSE_JAJUNI => 4,
    SIXEL_DIFFUSE_STUCKI => 5,
    SIXEL_DIFFUSE_BURKES => 6,
    SIXEL_DIFFUSE_A_DITHER => 7,
    SIXEL_DIFFUSE_X_DITHER => 8,
    SIXEL_DIFFUSE_BLUENOISE_DITHER => 9,
    SIXEL_DIFFUSE_LSO2 => 10,
    SIXEL_DIFFUSE_INTERFRAME => 11,
    SIXEL_DIFFUSE_SIERRA1 => 12,
    SIXEL_DIFFUSE_SIERRA2 => 13,
    SIXEL_DIFFUSE_SIERRA3 => 14,
    SIXEL_SCAN_AUTO => 0,
    SIXEL_SCAN_RASTER => 1,
    SIXEL_SCAN_SERPENTINE => 2,
    SIXEL_QUALITY_AUTO => 0,
    SIXEL_QUALITY_HIGH => 1,
    SIXEL_QUALITY_LOW => 2,
    SIXEL_QUALITY_FULL => 3,
    SIXEL_QUALITY_HIGHCOLOR => 4,
    SIXEL_LUT_POLICY_AUTO => 0,
    SIXEL_LUT_POLICY_5BIT => 1,
    SIXEL_LUT_POLICY_6BIT => 2,
    SIXEL_LUT_POLICY_NONE => 4,
    SIXEL_LUT_POLICY_CERTLUT => 5,
    SIXEL_LUT_POLICY_FHEDT => 6,
    SIXEL_LUT_POLICY_EYTZINGER => 7,
    SIXEL_LUT_POLICY_VPTREE => 8,
    SIXEL_LUT_POLICY_RBC => 9,
    SIXEL_LUT_POLICY_MAHALANOBIS => 10,
    SIXEL_BUILTIN_MONO_DARK => 0,
    SIXEL_BUILTIN_MONO_LIGHT => 1,
    SIXEL_BUILTIN_XTERM16 => 2,
    SIXEL_BUILTIN_XTERM256 => 3,
    SIXEL_BUILTIN_VT340_MONO => 4,
    SIXEL_BUILTIN_VT340_COLOR => 5,
    SIXEL_BUILTIN_G1 => 6,
    SIXEL_BUILTIN_G2 => 7,
    SIXEL_BUILTIN_G4 => 8,
    SIXEL_BUILTIN_G8 => 9,
    SIXEL_COLORSPACE_GAMMA => 0,
    SIXEL_COLORSPACE_LINEAR => 1,
    SIXEL_COLORSPACE_OKLAB => 2,
    SIXEL_COLORSPACE_SMPTEC => 3,
    SIXEL_COLORSPACE_CIELAB => 4,
    SIXEL_COLORSPACE_DIN99D => 5,
    SIXEL_FORMATTYPE_COLOR => 0,
    SIXEL_FORMATTYPE_GRAYSCALE => 64,
    SIXEL_FORMATTYPE_PALETTE => 128,
    SIXEL_DEQUANTIZE_NONE => 0,
    SIXEL_DEQUANTIZE_K_UNDITHER => 1,
    SIXEL_DEQUANTIZE_LSO_UNDITHER_VFS => 1,
    SIXEL_DEQUANTIZE_LSO_UNDITHER_VLIGHT => 2,
    SIXEL_QUANTIZE_MODEL_AUTO => 0,
    SIXEL_QUANTIZE_MODEL_MEDIANCUT => 1,
    SIXEL_QUANTIZE_MODEL_KMEANS => 2,
    SIXEL_QUANTIZE_MODEL_KMEDOIDS => 3,
    SIXEL_QUANTIZE_MODEL_KCENTER => 4,
    SIXEL_QUANTIZE_MODEL_STICKY => 5,
    SIXEL_FINAL_MERGE_AUTO => 0,
    SIXEL_FINAL_MERGE_NONE => 1,
    SIXEL_FINAL_MERGE_WARD => 2,
    SIXEL_PIXELFORMAT_RGB555 => 1,
    SIXEL_PIXELFORMAT_RGB565 => 2,
    SIXEL_PIXELFORMAT_RGB888 => 3,
    SIXEL_PIXELFORMAT_BGR555 => 4,
    SIXEL_PIXELFORMAT_BGR565 => 5,
    SIXEL_PIXELFORMAT_BGR888 => 6,
    SIXEL_PIXELFORMAT_ARGB8888 => 16,
    SIXEL_PIXELFORMAT_RGBA8888 => 17,
    SIXEL_PIXELFORMAT_ABGR8888 => 18,
    SIXEL_PIXELFORMAT_BGRA8888 => 19,
    SIXEL_PIXELFORMAT_RGBFLOAT32 => 32,
    SIXEL_PIXELFORMAT_LINEARRGBFLOAT32 => 33,
    SIXEL_PIXELFORMAT_OKLABFLOAT32 => 34,
    SIXEL_PIXELFORMAT_CIELABFLOAT32 => 35,
    SIXEL_PIXELFORMAT_DIN99DFLOAT32 => 36,
    SIXEL_PIXELFORMAT_G1 => 64,
    SIXEL_PIXELFORMAT_G2 => 65,
    SIXEL_PIXELFORMAT_G4 => 66,
    SIXEL_PIXELFORMAT_G8 => 67,
    SIXEL_PIXELFORMAT_AG88 => 83,
    SIXEL_PIXELFORMAT_GA88 => 99,
    SIXEL_PIXELFORMAT_PAL1 => 128,
    SIXEL_PIXELFORMAT_PAL2 => 129,
    SIXEL_PIXELFORMAT_PAL4 => 130,
    SIXEL_PIXELFORMAT_PAL8 => 131,
    SIXEL_PALETTETYPE_AUTO => 0,
    SIXEL_PALETTETYPE_HLS => 1,
    SIXEL_PALETTETYPE_RGB => 2,
    SIXEL_ENCODEPOLICY_AUTO => 0,
    SIXEL_ENCODEPOLICY_FAST => 1,
    SIXEL_ENCODEPOLICY_SIZE => 2,
    SIXEL_RES_NEAREST => 0,
    SIXEL_RES_GAUSSIAN => 1,
    SIXEL_RES_HANNING => 2,
    SIXEL_RES_HAMMING => 3,
    SIXEL_RES_BILINEAR => 4,
    SIXEL_RES_WELSH => 5,
    SIXEL_RES_BICUBIC => 6,
    SIXEL_RES_LANCZOS2 => 7,
    SIXEL_RES_LANCZOS3 => 8,
    SIXEL_RES_LANCZOS4 => 9,
    SIXEL_FORMAT_GIF => 0,
    SIXEL_FORMAT_PNG => 1,
    SIXEL_FORMAT_BMP => 2,
    SIXEL_FORMAT_JPG => 3,
    SIXEL_FORMAT_TGA => 4,
    SIXEL_FORMAT_WBMP => 5,
    SIXEL_FORMAT_TIFF => 6,
    SIXEL_FORMAT_SIXEL => 7,
    SIXEL_FORMAT_PNM => 8,
    SIXEL_FORMAT_GD2 => 9,
    SIXEL_FORMAT_PSD => 10,
    SIXEL_FORMAT_HDR => 11,
    SIXEL_LOOP_AUTO => 0,
    SIXEL_LOOP_FORCE => 1,
    SIXEL_LOOP_DISABLE => 2,
    SIXEL_TRANSPARENT_POLICY_COMPOSITE => 0,
    SIXEL_TRANSPARENT_POLICY_BACKGROUND => 1,
    SIXEL_TRANSPARENT_POLICY_KEEP => 2,
    SIXEL_TRANSPARENT_POLICY_P2_0 => 1,
    SIXEL_TRANSPARENT_POLICY_P2_1 => 2,
    SIXEL_6DELTA_ERROR_DIFFUSE => 0,
    SIXEL_6DELTA_ERROR_SKIP => 1,
    SIXEL_OPTFLAG_INPUT => 'i',
    SIXEL_OPTFLAG_OUTPUT => 'o',
    SIXEL_OPTFLAG_DEQUANTIZE => 'd',
    SIXEL_OPTFLAG_DIRECT => 'D',
    SIXEL_OPTFLAG_SIMILARITY => 'S',
    SIXEL_OPTFLAG_SIZE => 's',
    SIXEL_OPTFLAG_EDGE => 'e',
    SIXEL_OPTFLAG_OUTFILE => 'o',
    SIXEL_OPTFLAG_7BIT_MODE => '7',
    SIXEL_OPTFLAG_8BIT_MODE => '8',
    SIXEL_OPTFLAG_6REVERSIBLE => '6',
    SIXEL_OPTFLAG_HAS_GRI_ARG_LIMIT => 'R',
    SIXEL_OPTFLAG_PRECISION => '.',
    SIXEL_OPTFLAG_THREADS => '=',
    SIXEL_OPTFLAG_COLORS => 'p',
    SIXEL_OPTFLAG_MAPFILE => 'm',
    SIXEL_OPTFLAG_MAPFILE_OUTPUT => 'M',
    SIXEL_OPTFLAG_MONOCHROME => 'e',
    SIXEL_OPTFLAG_INSECURE => 'k',
    SIXEL_OPTFLAG_INVERT => 'i',
    SIXEL_OPTFLAG_HIGH_COLOR => 'I',
    SIXEL_OPTFLAG_USE_MACRO => 'u',
    SIXEL_OPTFLAG_MACRO_NUMBER => 'n',
    SIXEL_OPTFLAG_COMPLEXION_SCORE => 'C',
    SIXEL_OPTFLAG_IGNORE_DELAY => 'g',
    SIXEL_OPTFLAG_STATIC => 'S',
    SIXEL_OPTFLAG_DIFFUSION => 'd',
    SIXEL_OPTFLAG_FIND_LARGEST => 'f',
    SIXEL_OPTFLAG_SELECT_COLOR => 's',
    SIXEL_OPTFLAG_QUANTIZE_MODEL => 'Q',
    SIXEL_OPTFLAG_CROP => 'c',
    SIXEL_OPTFLAG_WIDTH => 'w',
    SIXEL_OPTFLAG_HEIGHT => 'h',
    SIXEL_OPTFLAG_RESAMPLING => 'r',
    SIXEL_OPTFLAG_QUALITY => 'q',
    SIXEL_OPTFLAG_LOOPMODE => 'l',
    SIXEL_OPTFLAG_START_FRAME => 'T',
    SIXEL_OPTFLAG_PALETTE_TYPE => 't',
    SIXEL_OPTFLAG_BUILTIN_PALETTE => 'b',
    SIXEL_OPTFLAG_ENCODE_POLICY => 'E',
    SIXEL_OPTFLAG_LUT_POLICY => '~',
    SIXEL_OPTFLAG_CLUSTERING_COLORSPACE => 'X',
    SIXEL_OPTFLAG_WORKING_COLORSPACE => 'W',
    SIXEL_OPTFLAG_OUTPUT_COLORSPACE => 'U',
    SIXEL_OPTFLAG_ORMODE => 'O',
    SIXEL_OPTFLAG_TRANSPARENT_POLICY => 'A',
    SIXEL_OPTFLAG_TRANSPARENT_OFFSET => '+',
    SIXEL_OPTFLAG_6DELTA_THRESHOLD => 'Z',
    SIXEL_OPTFLAG_6DELTA_ERROR => 'Y',
    SIXEL_OPTFLAG_BGCOLOR => 'B',
    SIXEL_OPTFLAG_PENETRATE => 'P',
    SIXEL_OPTFLAG_DRCS => '@',
    SIXEL_OPTFLAG_PIPE_MODE => 'D',
    SIXEL_OPTFLAG_VERBOSE => 'v',
    SIXEL_OPTFLAG_LOADERS => 'L',
    SIXEL_OPTFLAG_VERSION => 'V',
    SIXEL_OPTFLAG_HELP => 'H',
    SIXEL_LOADER_OPTION_REQUIRE_STATIC => 1,
    SIXEL_LOADER_OPTION_USE_PALETTE => 2,
    SIXEL_LOADER_OPTION_REQCOLORS => 3,
    SIXEL_LOADER_OPTION_BGCOLOR => 4,
    SIXEL_LOADER_OPTION_LOOP_CONTROL => 5,
    SIXEL_LOADER_OPTION_INSECURE => 6,
    SIXEL_LOADER_OPTION_CANCEL_FLAG => 7,
    SIXEL_LOADER_OPTION_LOADER_ORDER => 8,
    SIXEL_LOADER_OPTION_CONTEXT => 9,
    SIXEL_LOADER_OPTION_WIC_ICO_MINSIZE => 10,
    SIXEL_LOADER_OPTION_START_FRAME_NO => 11,
    SIXEL_LOADER_OPTION_BGCOLOR_SOURCE => 12,
    SIXEL_LOADER_BGCOLOR_SOURCE_EXPLICIT => 0,
    SIXEL_LOADER_BGCOLOR_SOURCE_ENV => 1,
};

1;
