package Image::LibSIXEL::GeneratedAttach;
use strict;
use warnings;

sub attach_all {
    my ($ffi) = @_;

    # Callback typedefs are mapped to explicit Platypus signatures.
    $ffi->type('(opaque,opaque)->int' => 'sixel_loader_callback_t');
    $ffi->type('(opaque,int,opaque)->int' => 'sixel_write_callback_t');

    $ffi->attach(['sixel_allocator_new' => 'Image::LibSIXEL::sixel_allocator_new'] => ['opaque*', 'opaque', 'opaque', 'opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_allocator_ref' => 'Image::LibSIXEL::sixel_allocator_ref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_allocator_unref' => 'Image::LibSIXEL::sixel_allocator_unref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_allocator_malloc' => 'Image::LibSIXEL::sixel_allocator_malloc'] => ['opaque', 'int'] => 'opaque');
    $ffi->attach(['sixel_allocator_calloc' => 'Image::LibSIXEL::sixel_allocator_calloc'] => ['opaque', 'int', 'int'] => 'opaque');
    $ffi->attach(['sixel_allocator_realloc' => 'Image::LibSIXEL::sixel_allocator_realloc'] => ['opaque', 'opaque', 'int'] => 'opaque');
    $ffi->attach(['sixel_allocator_free' => 'Image::LibSIXEL::sixel_allocator_free'] => ['opaque', 'opaque'] => 'void');
    $ffi->attach(['sixel_output_new' => 'Image::LibSIXEL::_sixel_output_new'] => ['opaque*', 'sixel_write_callback_t', 'opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_output_create' => 'Image::LibSIXEL::sixel_output_create'] => ['sixel_write_callback_t', 'opaque'] => 'opaque');
    $ffi->attach(['sixel_output_destroy' => 'Image::LibSIXEL::sixel_output_destroy'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_output_ref' => 'Image::LibSIXEL::sixel_output_ref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_output_unref' => 'Image::LibSIXEL::sixel_output_unref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_output_get_8bit_availability' => 'Image::LibSIXEL::sixel_output_get_8bit_availability'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_output_set_8bit_availability' => 'Image::LibSIXEL::sixel_output_set_8bit_availability'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_output_set_gri_arg_limit' => 'Image::LibSIXEL::sixel_output_set_gri_arg_limit'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_output_set_penetrate_multiplexer' => 'Image::LibSIXEL::sixel_output_set_penetrate_multiplexer'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_output_set_skip_dcs_envelope' => 'Image::LibSIXEL::sixel_output_set_skip_dcs_envelope'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_output_set_skip_header' => 'Image::LibSIXEL::sixel_output_set_skip_header'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_output_set_palette_type' => 'Image::LibSIXEL::sixel_output_set_palette_type'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_output_set_ormode' => 'Image::LibSIXEL::sixel_output_set_ormode'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_output_set_encode_policy' => 'Image::LibSIXEL::sixel_output_set_encode_policy'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_output_convert_colorspace' => 'Image::LibSIXEL::sixel_output_convert_colorspace'] => ['opaque', 'opaque', 'int'] => 'int');
    $ffi->attach(['sixel_palette_new' => 'Image::LibSIXEL::sixel_palette_new'] => ['opaque*', 'opaque'] => 'int');
    $ffi->attach(['sixel_palette_ref' => 'Image::LibSIXEL::sixel_palette_ref'] => ['opaque'] => 'opaque');
    $ffi->attach(['sixel_palette_unref' => 'Image::LibSIXEL::sixel_palette_unref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_palette_resize' => 'Image::LibSIXEL::sixel_palette_resize'] => ['opaque', 'int', 'int', 'opaque'] => 'int');
    $ffi->attach(['sixel_palette_set_entries' => 'Image::LibSIXEL::sixel_palette_set_entries'] => ['opaque', 'opaque', 'int', 'int', 'opaque'] => 'int');
    $ffi->attach(['sixel_palette_set_entries_float32' => 'Image::LibSIXEL::sixel_palette_set_entries_float32'] => ['opaque', 'opaque', 'int', 'int', 'opaque'] => 'int');
    $ffi->attach(['sixel_palette_copy_entries_8bit' => 'Image::LibSIXEL::sixel_palette_copy_entries_8bit'] => ['opaque', 'opaque*', 'opaque', 'int', 'opaque'] => 'int');
    $ffi->attach(['sixel_palette_copy_entries_float32' => 'Image::LibSIXEL::sixel_palette_copy_entries_float32'] => ['opaque', 'opaque*', 'opaque', 'int', 'opaque'] => 'int');
    $ffi->attach(['sixel_dither_new' => 'Image::LibSIXEL::_sixel_dither_new'] => ['opaque*', 'int', 'opaque'] => 'int');
    $ffi->attach(['sixel_dither_create' => 'Image::LibSIXEL::sixel_dither_create'] => ['int'] => 'opaque');
    $ffi->attach(['sixel_dither_get' => 'Image::LibSIXEL::sixel_dither_get'] => ['int'] => 'opaque');
    $ffi->attach(['sixel_dither_destroy' => 'Image::LibSIXEL::sixel_dither_destroy'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_dither_ref' => 'Image::LibSIXEL::sixel_dither_ref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_dither_unref' => 'Image::LibSIXEL::sixel_dither_unref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_dither_initialize' => 'Image::LibSIXEL::_sixel_dither_initialize'] => ['opaque', 'opaque', 'int', 'int', 'int', 'int', 'int', 'int'] => 'int');
    $ffi->attach(['sixel_dither_set_lut_policy' => 'Image::LibSIXEL::sixel_dither_set_lut_policy'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_get_lut_policy' => 'Image::LibSIXEL::sixel_dither_get_lut_policy'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_dither_set_diffusion_type' => 'Image::LibSIXEL::sixel_dither_set_diffusion_type'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_set_diffusion_scan' => 'Image::LibSIXEL::sixel_dither_set_diffusion_scan'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_set_diffusion_carry' => 'Image::LibSIXEL::sixel_dither_set_diffusion_carry'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_get_num_of_palette_colors' => 'Image::LibSIXEL::sixel_dither_get_num_of_palette_colors'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_dither_get_num_of_histogram_colors' => 'Image::LibSIXEL::sixel_dither_get_num_of_histogram_colors'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_dither_get_num_of_histgram_colors' => 'Image::LibSIXEL::sixel_dither_get_num_of_histgram_colors'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_dither_get_palette' => 'Image::LibSIXEL::sixel_dither_get_palette'] => ['opaque'] => 'opaque');
    $ffi->attach(['sixel_dither_get_quantized_palette' => 'Image::LibSIXEL::sixel_dither_get_quantized_palette'] => ['opaque', 'opaque*'] => 'int');
    $ffi->attach(['sixel_dither_set_palette' => 'Image::LibSIXEL::sixel_dither_set_palette'] => ['opaque', 'opaque'] => 'void');
    $ffi->attach(['sixel_dither_set_complexion_score' => 'Image::LibSIXEL::sixel_dither_set_complexion_score'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_set_body_only' => 'Image::LibSIXEL::sixel_dither_set_body_only'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_set_optimize_palette' => 'Image::LibSIXEL::sixel_dither_set_optimize_palette'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_set_pixelformat' => 'Image::LibSIXEL::sixel_dither_set_pixelformat'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_set_sixel_reversible' => 'Image::LibSIXEL::sixel_dither_set_sixel_reversible'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_set_final_merge' => 'Image::LibSIXEL::sixel_dither_set_final_merge'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_dither_set_transparent' => 'Image::LibSIXEL::sixel_dither_set_transparent'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_encode' => 'Image::LibSIXEL::sixel_encode'] => ['opaque', 'int', 'int', 'int', 'opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_decode_raw' => 'Image::LibSIXEL::sixel_decode_raw'] => ['opaque', 'int', 'opaque*', 'opaque', 'opaque', 'opaque*', 'opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_decode_direct' => 'Image::LibSIXEL::sixel_decode_direct'] => ['opaque', 'int', 'opaque*', 'opaque', 'opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_decode_rgba' => 'Image::LibSIXEL::sixel_decode_rgba'] => ['opaque', 'int', 'int', 'opaque', 'opaque*', 'opaque', 'opaque', 'opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_decode' => 'Image::LibSIXEL::sixel_decode'] => ['opaque', 'int', 'opaque*', 'opaque', 'opaque', 'opaque*', 'opaque', 'int'] => 'int');
    $ffi->attach(['sixel_tty_init_output_device' => 'Image::LibSIXEL::sixel_tty_init_output_device'] => ['int'] => 'void');
    $ffi->attach(['sixel_helper_set_additional_message' => 'Image::LibSIXEL::sixel_helper_set_additional_message'] => ['string'] => 'void');
    $ffi->attach(['sixel_helper_get_additional_message' => 'Image::LibSIXEL::sixel_helper_get_additional_message'] => [] => 'string');
    $ffi->attach(['sixel_helper_format_error' => 'Image::LibSIXEL::_sixel_helper_format_error'] => ['int'] => 'string');
    $ffi->attach(['sixel_helper_compute_depth' => 'Image::LibSIXEL::sixel_helper_compute_depth'] => ['int'] => 'int');
    $ffi->attach(['sixel_helper_normalize_pixelformat' => 'Image::LibSIXEL::sixel_helper_normalize_pixelformat'] => ['opaque', 'opaque', 'opaque', 'int', 'int', 'int'] => 'int');
    $ffi->attach(['sixel_helper_scale_image' => 'Image::LibSIXEL::sixel_helper_scale_image'] => ['opaque', 'opaque', 'int', 'int', 'int', 'int', 'int', 'int', 'opaque'] => 'int');
    $ffi->attach(['sixel_helper_convert_colorspace' => 'Image::LibSIXEL::sixel_helper_convert_colorspace'] => ['opaque', 'int', 'int', 'int', 'int'] => 'int');
    $ffi->attach(['sixel_option_apply_cli_suggestion_defaults' => 'Image::LibSIXEL::sixel_option_apply_cli_suggestion_defaults'] => [] => 'void');
    $ffi->attach(['sixel_frame_new' => 'Image::LibSIXEL::_sixel_frame_new'] => ['opaque*', 'opaque'] => 'int');
    $ffi->attach(['sixel_frame_create' => 'Image::LibSIXEL::sixel_frame_create'] => [] => 'opaque');
    $ffi->attach(['sixel_frame_ref' => 'Image::LibSIXEL::sixel_frame_ref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_frame_unref' => 'Image::LibSIXEL::sixel_frame_unref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_frame_init' => 'Image::LibSIXEL::sixel_frame_init'] => ['opaque', 'opaque', 'int', 'int', 'int', 'opaque', 'int'] => 'int');
    $ffi->attach(['sixel_frame_init_float32' => 'Image::LibSIXEL::sixel_frame_init_float32'] => ['opaque', 'opaque', 'int', 'int', 'int', 'opaque', 'int'] => 'int');
    $ffi->attach(['sixel_frame_get_pixels' => 'Image::LibSIXEL::sixel_frame_get_pixels'] => ['opaque'] => 'opaque');
    $ffi->attach(['sixel_frame_get_pixels_float32' => 'Image::LibSIXEL::sixel_frame_get_pixels_float32'] => ['opaque'] => 'opaque');
    $ffi->attach(['sixel_frame_set_pixels' => 'Image::LibSIXEL::sixel_frame_set_pixels'] => ['opaque', 'opaque'] => 'void');
    $ffi->attach(['sixel_frame_set_pixels_float32' => 'Image::LibSIXEL::sixel_frame_set_pixels_float32'] => ['opaque', 'opaque'] => 'void');
    $ffi->attach(['sixel_frame_get_palette' => 'Image::LibSIXEL::sixel_frame_get_palette'] => ['opaque'] => 'opaque');
    $ffi->attach(['sixel_frame_set_palette' => 'Image::LibSIXEL::sixel_frame_set_palette'] => ['opaque', 'opaque'] => 'void');
    $ffi->attach(['sixel_frame_get_width' => 'Image::LibSIXEL::sixel_frame_get_width'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_width' => 'Image::LibSIXEL::sixel_frame_set_width'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_frame_get_height' => 'Image::LibSIXEL::sixel_frame_get_height'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_height' => 'Image::LibSIXEL::sixel_frame_set_height'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_frame_get_ncolors' => 'Image::LibSIXEL::sixel_frame_get_ncolors'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_ncolors' => 'Image::LibSIXEL::sixel_frame_set_ncolors'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_frame_get_pixelformat' => 'Image::LibSIXEL::sixel_frame_get_pixelformat'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_pixelformat' => 'Image::LibSIXEL::sixel_frame_set_pixelformat'] => ['opaque', 'int'] => 'int');
    $ffi->attach(['sixel_frame_get_colorspace' => 'Image::LibSIXEL::sixel_frame_get_colorspace'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_colorspace' => 'Image::LibSIXEL::sixel_frame_set_colorspace'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_frame_get_transparent' => 'Image::LibSIXEL::sixel_frame_get_transparent'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_transparent' => 'Image::LibSIXEL::sixel_frame_set_transparent'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_frame_get_multiframe' => 'Image::LibSIXEL::sixel_frame_get_multiframe'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_multiframe' => 'Image::LibSIXEL::sixel_frame_set_multiframe'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_frame_get_delay' => 'Image::LibSIXEL::sixel_frame_get_delay'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_delay' => 'Image::LibSIXEL::sixel_frame_set_delay'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_frame_get_frame_no' => 'Image::LibSIXEL::sixel_frame_get_frame_no'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_frame_no' => 'Image::LibSIXEL::sixel_frame_set_frame_no'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_frame_increment_frame_no' => 'Image::LibSIXEL::sixel_frame_increment_frame_no'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_frame_reset_frame_no' => 'Image::LibSIXEL::sixel_frame_reset_frame_no'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_frame_get_loop_no' => 'Image::LibSIXEL::sixel_frame_get_loop_no'] => ['opaque'] => 'int');
    $ffi->attach(['sixel_frame_set_loop_count' => 'Image::LibSIXEL::sixel_frame_set_loop_count'] => ['opaque', 'int'] => 'void');
    $ffi->attach(['sixel_frame_increment_loop_count' => 'Image::LibSIXEL::sixel_frame_increment_loop_count'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_frame_get_allocator' => 'Image::LibSIXEL::sixel_frame_get_allocator'] => ['opaque'] => 'opaque');
    $ffi->attach(['sixel_frame_strip_alpha' => 'Image::LibSIXEL::sixel_frame_strip_alpha'] => ['opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_frame_resize' => 'Image::LibSIXEL::sixel_frame_resize'] => ['opaque', 'int', 'int', 'int'] => 'int');
    $ffi->attach(['sixel_frame_resize_float32' => 'Image::LibSIXEL::sixel_frame_resize_float32'] => ['opaque', 'int', 'int', 'int'] => 'int');
    $ffi->attach(['sixel_frame_clip' => 'Image::LibSIXEL::sixel_frame_clip'] => ['opaque', 'int', 'int', 'int', 'int'] => 'int');
    $ffi->attach(['sixel_loader_new' => 'Image::LibSIXEL::_sixel_loader_new'] => ['opaque*', 'opaque'] => 'int');
    $ffi->attach(['sixel_loader_ref' => 'Image::LibSIXEL::sixel_loader_ref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_loader_unref' => 'Image::LibSIXEL::sixel_loader_unref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_loader_setopt' => 'Image::LibSIXEL::_sixel_loader_setopt'] => ['opaque', 'int', 'opaque'] => 'int');
    $ffi->attach(['sixel_loader_load_file' => 'Image::LibSIXEL::_sixel_loader_load_file'] => ['opaque', 'string', 'sixel_loader_callback_t'] => 'int');
    $ffi->attach(['sixel_helper_load_image_file' => 'Image::LibSIXEL::sixel_helper_load_image_file'] => ['string', 'int', 'int', 'int', 'opaque', 'int', 'sixel_loader_callback_t', 'int', 'opaque', 'opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_helper_get_available_loader_names' => 'Image::LibSIXEL::sixel_helper_get_available_loader_names'] => ['opaque*', 'int'] => 'int');
    $ffi->attach(['sixel_probe_is_probable' => 'Image::LibSIXEL::sixel_probe_is_probable'] => ['opaque', 'int'] => 'int');
    $ffi->attach(['sixel_parse_header' => 'Image::LibSIXEL::sixel_parse_header'] => ['opaque', 'int', 'opaque*', 'opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_helper_write_image_file' => 'Image::LibSIXEL::sixel_helper_write_image_file'] => ['opaque', 'int', 'int', 'opaque', 'int', 'string', 'int', 'opaque'] => 'int');
    $ffi->attach(['sixel_encoder_new' => 'Image::LibSIXEL::_sixel_encoder_new'] => ['opaque*', 'opaque'] => 'int');
    $ffi->attach(['sixel_encoder_create' => 'Image::LibSIXEL::sixel_encoder_create'] => [] => 'opaque');
    $ffi->attach(['sixel_encoder_ref' => 'Image::LibSIXEL::sixel_encoder_ref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_encoder_unref' => 'Image::LibSIXEL::_sixel_encoder_unref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_encoder_set_cancel_flag' => 'Image::LibSIXEL::sixel_encoder_set_cancel_flag'] => ['opaque', 'opaque'] => 'int');
    $ffi->attach(['sixel_encoder_setopt' => 'Image::LibSIXEL::_sixel_encoder_setopt'] => ['opaque', 'int', 'string'] => 'int');
    $ffi->attach(['sixel_encoder_encode' => 'Image::LibSIXEL::_sixel_encoder_encode'] => ['opaque', 'string'] => 'int');
    $ffi->attach(['sixel_encoder_encode_bytes' => 'Image::LibSIXEL::sixel_encoder_encode_bytes'] => ['opaque', 'opaque', 'int', 'int', 'int', 'opaque', 'int'] => 'int');
    $ffi->attach(['sixel_encoder_enable_quantized_capture' => 'Image::LibSIXEL::sixel_encoder_enable_quantized_capture'] => ['opaque', 'int'] => 'int');
    $ffi->attach(['sixel_encoder_enable_source_capture' => 'Image::LibSIXEL::sixel_encoder_enable_source_capture'] => ['opaque', 'int'] => 'int');
    $ffi->attach(['sixel_encoder_copy_quantized_frame' => 'Image::LibSIXEL::sixel_encoder_copy_quantized_frame'] => ['opaque', 'opaque', 'opaque*'] => 'int');
    $ffi->attach(['sixel_encoder_copy_source_frame' => 'Image::LibSIXEL::sixel_encoder_copy_source_frame'] => ['opaque', 'opaque*'] => 'int');
    $ffi->attach(['sixel_decoder_new' => 'Image::LibSIXEL::_sixel_decoder_new'] => ['opaque*', 'opaque'] => 'int');
    $ffi->attach(['sixel_decoder_create' => 'Image::LibSIXEL::sixel_decoder_create'] => [] => 'opaque');
    $ffi->attach(['sixel_decoder_ref' => 'Image::LibSIXEL::sixel_decoder_ref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_decoder_unref' => 'Image::LibSIXEL::_sixel_decoder_unref'] => ['opaque'] => 'void');
    $ffi->attach(['sixel_decoder_setopt' => 'Image::LibSIXEL::_sixel_decoder_setopt'] => ['opaque', 'int', 'string'] => 'int');
    $ffi->attach(['sixel_decoder_decode' => 'Image::LibSIXEL::_sixel_decoder_decode'] => ['opaque'] => 'int');

    return;
}

1;
