/*
 * SPDX-License-Identifier: MIT
 *
 * Copyright (c) 2026 libsixel developers. See `AUTHORS`.
 */

#if defined(HAVE_CONFIG_H)
# include "config.h"
#endif

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "fuzz-loader-builtin-struct-common.h"

extern size_t LLVMFuzzerMutate(uint8_t *data, size_t size, size_t max_size);

enum fuzz_gif_lzw_feature {
    FUZZ_GIF_LZW_FEATURE_HEADER = 0,
    FUZZ_GIF_LZW_FEATURE_GCE,
    FUZZ_GIF_LZW_FEATURE_TRANSPARENT_GCE,
    FUZZ_GIF_LZW_FEATURE_INTERLACE,
    FUZZ_GIF_LZW_FEATURE_LARGE_MIN_CODE,
    FUZZ_GIF_LZW_FEATURE_CLEAR,
    FUZZ_GIF_LZW_FEATURE_EOI,
    FUZZ_GIF_LZW_FEATURE_LITERAL,
    FUZZ_GIF_LZW_FEATURE_DICT,
    FUZZ_GIF_LZW_FEATURE_WIDTH_GROW,
    FUZZ_GIF_LZW_FEATURE_SUBBLOCK,
    FUZZ_GIF_LZW_FEATURE_LONG_SUBBLOCK,
    FUZZ_GIF_LZW_FEATURE_EARLY_END,
    FUZZ_GIF_LZW_FEATURE_COUNT
};

static unsigned int g_gif_lzw_feature_mask = 0u;
static unsigned int g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_COUNT];
static int g_gif_lzw_stats_registered = 0;

#define FUZZ_GIF_LZW_RECORD_FEATURE(_feature) \
    do { \
        g_gif_lzw_feature_mask |= 1u << (_feature); \
        ++g_gif_lzw_feature_hits[(_feature)]; \
    } while (0)

static unsigned int
fuzz_gif_lzw_count_bits(unsigned int value)
{
    unsigned int count;

    count = 0u;
    while (value != 0u) {
        count += value & 1u;
        value >>= 1;
    }

    return count;
}

static void
fuzz_gif_lzw_note_feature(unsigned int feature)
{
    if (feature >= FUZZ_GIF_LZW_FEATURE_COUNT) {
        return;
    }

    /*
     * GIF LZW streams are stateful enough that plain edge coverage can miss
     * whether generated bytes reached distinct decoder states. These feature
     * branches make grammar milestones visible to coverage-guided fuzzers.
     */
    switch (feature) {
    case FUZZ_GIF_LZW_FEATURE_HEADER:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_HEADER);
        break;
    case FUZZ_GIF_LZW_FEATURE_GCE:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_GCE);
        break;
    case FUZZ_GIF_LZW_FEATURE_TRANSPARENT_GCE:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_TRANSPARENT_GCE);
        break;
    case FUZZ_GIF_LZW_FEATURE_INTERLACE:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_INTERLACE);
        break;
    case FUZZ_GIF_LZW_FEATURE_LARGE_MIN_CODE:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_LARGE_MIN_CODE);
        break;
    case FUZZ_GIF_LZW_FEATURE_CLEAR:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_CLEAR);
        break;
    case FUZZ_GIF_LZW_FEATURE_EOI:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_EOI);
        break;
    case FUZZ_GIF_LZW_FEATURE_LITERAL:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_LITERAL);
        break;
    case FUZZ_GIF_LZW_FEATURE_DICT:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_DICT);
        break;
    case FUZZ_GIF_LZW_FEATURE_WIDTH_GROW:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_WIDTH_GROW);
        break;
    case FUZZ_GIF_LZW_FEATURE_SUBBLOCK:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_SUBBLOCK);
        break;
    case FUZZ_GIF_LZW_FEATURE_LONG_SUBBLOCK:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_LONG_SUBBLOCK);
        break;
    case FUZZ_GIF_LZW_FEATURE_EARLY_END:
        FUZZ_GIF_LZW_RECORD_FEATURE(FUZZ_GIF_LZW_FEATURE_EARLY_END);
        break;
    default:
        break;
    }
}

static void
fuzz_gif_lzw_print_semantic_stats(void)
{
    fprintf(stderr,
            "gif-lzw-semantic-features: mask=0x%08x count=%u "
            "header=%u gce=%u transparent-gce=%u interlace=%u "
            "large-min-code=%u clear=%u eoi=%u literal=%u dict=%u "
            "width-grow=%u subblock=%u long-subblock=%u early-end=%u\n",
            g_gif_lzw_feature_mask,
            fuzz_gif_lzw_count_bits(g_gif_lzw_feature_mask),
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_HEADER],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_GCE],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_TRANSPARENT_GCE],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_INTERLACE],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_LARGE_MIN_CODE],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_CLEAR],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_EOI],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_LITERAL],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_DICT],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_WIDTH_GROW],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_SUBBLOCK],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_LONG_SUBBLOCK],
            g_gif_lzw_feature_hits[FUZZ_GIF_LZW_FEATURE_EARLY_END]);
}

static void
fuzz_gif_lzw_register_semantic_stats(void)
{
    if (g_gif_lzw_stats_registered) {
        return;
    }

    (void)atexit(fuzz_gif_lzw_print_semantic_stats);
    g_gif_lzw_stats_registered = 1;
}

static uint32_t
fuzz_gif_lzw_mutator_next(uint32_t *state)
{
    uint32_t value;

    value = *state;
    value ^= value << 13;
    value ^= value >> 17;
    value ^= value << 5;
    if (value == 0u) {
        value = UINT32_C(0x6d2b79f5);
    }
    *state = value;

    return value;
}

static int
fuzz_gif_lzw_mutator_append_u8(uint8_t *data,
                               size_t *pos,
                               size_t max_size,
                               unsigned char value)
{
    if (data == NULL || pos == NULL || *pos >= max_size) {
        return 0;
    }

    data[*pos] = value;
    ++*pos;
    return 1;
}

static int
fuzz_gif_lzw_mutator_append_next(uint8_t *data,
                                 size_t *pos,
                                 size_t max_size,
                                 uint32_t *state)
{
    return fuzz_gif_lzw_mutator_append_u8(
        data,
        pos,
        max_size,
        (unsigned char)fuzz_gif_lzw_mutator_next(state));
}

static int
fuzz_gif_lzw_mutator_append_span(uint8_t *data,
                                 size_t *pos,
                                 size_t max_size,
                                 uint8_t const *source,
                                 size_t source_size)
{
    size_t copy_size;

    if (data == NULL || pos == NULL || source == NULL || *pos >= max_size) {
        return 0;
    }

    copy_size = source_size;
    if (copy_size > max_size - *pos) {
        copy_size = max_size - *pos;
    }
    if (copy_size == 0u) {
        return 1;
    }

    memcpy(data + *pos, source, copy_size);
    *pos += copy_size;
    return 1;
}

static unsigned int
fuzz_gif_lzw_mutator_choose_focus(uint32_t *state)
{
    unsigned int feature;
    unsigned int best;
    unsigned int hits;
    unsigned int best_hits;

    if (state == NULL) {
        return FUZZ_GIF_LZW_FEATURE_HEADER;
    }

    best = (unsigned int)(fuzz_gif_lzw_mutator_next(state) %
                          FUZZ_GIF_LZW_FEATURE_COUNT);
    best_hits = g_gif_lzw_feature_hits[best];
    for (feature = 0u; feature < FUZZ_GIF_LZW_FEATURE_COUNT; ++feature) {
        hits = g_gif_lzw_feature_hits[feature];
        if (hits < best_hits ||
            (hits == best_hits &&
             (fuzz_gif_lzw_mutator_next(state) & 0x01u) != 0u)) {
            best = feature;
            best_hits = hits;
        }
    }

    return best;
}

static size_t
fuzz_gif_lzw_mutator_control_prefix(uint8_t const *data, size_t size)
{
    unsigned int min_code_size;
    unsigned int color_table_entries;
    size_t prefix_size;

    if (data == NULL || size == 0u) {
        return 0u;
    }

    min_code_size = 2u + (unsigned int)(data[0] % 4u);
    color_table_entries = 1u << min_code_size;
    prefix_size = 3u + (size_t)color_table_entries * 3u + 8u;
    if (prefix_size > size) {
        prefix_size = size;
    }

    return prefix_size;
}

static size_t
fuzz_gif_lzw_mutator_synthesize(uint8_t *data,
                                size_t max_size,
                                uint32_t *state,
                                unsigned int focus)
{
    size_t pos;
    unsigned int min_selector;
    unsigned int min_code_size;
    unsigned int color_table_entries;
    unsigned int i;
    unsigned int op_count;
    unsigned int dict_code;
    unsigned char gce_flag;
    unsigned char gce_packed;
    unsigned char image_packed;

    if (data == NULL || state == NULL || max_size == 0u) {
        return 0u;
    }

    pos = 0u;
    if (focus == FUZZ_GIF_LZW_FEATURE_LARGE_MIN_CODE ||
        focus == FUZZ_GIF_LZW_FEATURE_WIDTH_GROW ||
        focus == FUZZ_GIF_LZW_FEATURE_DICT) {
        min_selector = 3u;
    } else {
        min_selector = fuzz_gif_lzw_mutator_next(state) & 0x03u;
    }
    min_code_size = 2u + min_selector;
    color_table_entries = 1u << min_code_size;

    if (!fuzz_gif_lzw_mutator_append_u8(data,
                                        &pos,
                                        max_size,
                                        (unsigned char)min_selector) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 95u) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 95u)) {
        return pos;
    }

    for (i = 0u; i < color_table_entries; ++i) {
        if (!fuzz_gif_lzw_mutator_append_next(data,
                                              &pos,
                                              max_size,
                                              state) ||
            !fuzz_gif_lzw_mutator_append_next(data,
                                              &pos,
                                              max_size,
                                              state) ||
            !fuzz_gif_lzw_mutator_append_next(data,
                                              &pos,
                                              max_size,
                                              state)) {
            return pos;
        }
    }

    gce_flag = 1u;
    gce_packed = focus == FUZZ_GIF_LZW_FEATURE_TRANSPARENT_GCE
        ? 1u
        : (unsigned char)(fuzz_gif_lzw_mutator_next(state) & 0x1fu);
    image_packed = focus == FUZZ_GIF_LZW_FEATURE_INTERLACE
        ? 0x40u
        : (unsigned char)(fuzz_gif_lzw_mutator_next(state) & 0x40u);
    if (!fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, gce_flag) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, gce_packed) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 0u) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 1u) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 0u) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 0u) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 0u) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, image_packed)) {
        return pos;
    }

    op_count = focus == FUZZ_GIF_LZW_FEATURE_WIDTH_GROW ||
               focus == FUZZ_GIF_LZW_FEATURE_DICT ? 128u : 64u;
    if (!fuzz_gif_lzw_mutator_append_u8(data,
                                        &pos,
                                        max_size,
                                        (unsigned char)(op_count - 4u))) {
        return pos;
    }

    for (i = 0u; i < op_count; ++i) {
        dict_code = (1u << min_code_size) + 2u + (i % 16u);
        if (!fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 3u) ||
            !fuzz_gif_lzw_mutator_append_u8(data,
                                            &pos,
                                            max_size,
                                            (unsigned char)(dict_code >> 8)) ||
            !fuzz_gif_lzw_mutator_append_u8(data,
                                            &pos,
                                            max_size,
                                            (unsigned char)
                                                (dict_code & 0xffu))) {
            return pos;
        }
    }

    if (!fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 63u) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 1u) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 0u) ||
        !fuzz_gif_lzw_mutator_append_u8(data, &pos, max_size, 0u)) {
        return pos;
    }

    return pos;
}

static int
fuzz_gif_pack_code(fuzz_byte_buffer_t *stream,
                   uint32_t *bit_acc,
                   unsigned int *bit_count,
                   uint16_t code,
                   unsigned int width)
{
    if (stream == NULL || bit_acc == NULL || bit_count == NULL) {
        return 0;
    }
    if (width == 0u || width > 12u) {
        return 0;
    }

    *bit_acc |= ((uint32_t)code << *bit_count);
    *bit_count += width;

    while (*bit_count >= 8u) {
        unsigned char out;

        out = (unsigned char)(*bit_acc & 0xffu);
        if (!fuzz_byte_buffer_append_u8(stream, out)) {
            return 0;
        }
        *bit_acc >>= 8u;
        *bit_count -= 8u;
    }

    return 1;
}

size_t
LLVMFuzzerCustomMutator(uint8_t *data,
                        size_t size,
                        size_t max_size,
                        unsigned int seed)
{
    uint32_t state;
    size_t mutated_size;
    unsigned int focus;

    if (data == NULL || max_size == 0u) {
        return 0u;
    }

    state = (uint32_t)seed ^ (uint32_t)size ^ UINT32_C(0x9e3779b9);
    focus = fuzz_gif_lzw_mutator_choose_focus(&state);
    if (size != 0u && (fuzz_gif_lzw_mutator_next(&state) & 0x07u) == 0u) {
        mutated_size = LLVMFuzzerMutate(data, size, max_size);
        if (mutated_size != 0u) {
            return mutated_size;
        }
    }

    return fuzz_gif_lzw_mutator_synthesize(data, max_size, &state, focus);
}

size_t
LLVMFuzzerCustomCrossOver(uint8_t const *data1,
                          size_t size1,
                          uint8_t const *data2,
                          size_t size2,
                          uint8_t *out,
                          size_t max_out_size,
                          unsigned int seed)
{
    uint32_t state;
    size_t pos;
    size_t prefix_size;
    size_t suffix_offset;
    uint8_t const *prefix_data;
    uint8_t const *suffix_data;
    size_t prefix_data_size;
    size_t suffix_data_size;
    unsigned int focus;

    if (out == NULL || max_out_size == 0u) {
        return 0u;
    }

    state = (uint32_t)seed ^ (uint32_t)size1 ^
            ((uint32_t)size2 << 1) ^ UINT32_C(0x165667b1);
    focus = fuzz_gif_lzw_mutator_choose_focus(&state);
    if ((fuzz_gif_lzw_mutator_next(&state) & 0x01u) == 0u) {
        prefix_data = data1;
        prefix_data_size = size1;
        suffix_data = data2;
        suffix_data_size = size2;
    } else {
        prefix_data = data2;
        prefix_data_size = size2;
        suffix_data = data1;
        suffix_data_size = size1;
    }

    pos = 0u;
    prefix_size = fuzz_gif_lzw_mutator_control_prefix(prefix_data,
                                                     prefix_data_size);
    if (prefix_size > 0u) {
        (void)fuzz_gif_lzw_mutator_append_span(out,
                                               &pos,
                                               max_out_size,
                                               prefix_data,
                                               prefix_size);
    }

    suffix_offset = fuzz_gif_lzw_mutator_control_prefix(suffix_data,
                                                       suffix_data_size);
    if (suffix_offset >= suffix_data_size) {
        suffix_offset = suffix_data_size / 2u;
    }
    if (suffix_offset < suffix_data_size) {
        (void)fuzz_gif_lzw_mutator_append_span(out,
                                               &pos,
                                               max_out_size,
                                               suffix_data + suffix_offset,
                                               suffix_data_size -
                                                   suffix_offset);
    }
    if (pos == 0u) {
        return fuzz_gif_lzw_mutator_synthesize(out,
                                               max_out_size,
                                               &state,
                                               focus);
    }
    if (focus == FUZZ_GIF_LZW_FEATURE_LARGE_MIN_CODE && pos > 0u) {
        out[0] = 3u;
    }

    return pos;
}

static int
fuzz_gif_flush_codes(fuzz_byte_buffer_t *stream,
                     uint32_t *bit_acc,
                     unsigned int *bit_count)
{
    if (stream == NULL || bit_acc == NULL || bit_count == NULL) {
        return 0;
    }

    if (*bit_count > 0u) {
        if (!fuzz_byte_buffer_append_u8(
                stream,
                (unsigned char)(*bit_acc & 0xffu))) {
            return 0;
        }
        *bit_acc = 0u;
        *bit_count = 0u;
    }

    return 1;
}

static int
fuzz_build_gif_lzw_stream(fuzz_cursor_t *cursor,
                          unsigned int min_code_size,
                          fuzz_byte_buffer_t *stream)
{
    uint16_t clear_code;
    uint16_t eoi_code;
    uint16_t next_code;
    unsigned int code_size;
    unsigned int max_code_value;
    uint32_t bit_acc;
    unsigned int bit_count;
    int saw_eoi;
    int prev_was_clear;
    size_t i;
    size_t op_count;
    unsigned char op;
    uint16_t code;
    uint16_t upper;
    uint16_t code_sample;

    if (cursor == NULL || stream == NULL ||
        min_code_size < 2u || min_code_size > 8u) {
        return 0;
    }

    clear_code = (uint16_t)(1u << min_code_size);
    eoi_code = (uint16_t)(clear_code + 1u);
    next_code = (uint16_t)(eoi_code + 1u);
    code_size = min_code_size + 1u;
    max_code_value = 1u << code_size;
    bit_acc = 0u;
    bit_count = 0u;
    saw_eoi = 0;
    prev_was_clear = 1;

    if (!fuzz_gif_pack_code(stream,
                            &bit_acc,
                            &bit_count,
                            clear_code,
                            code_size)) {
        return 0;
    }
    fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_CLEAR);

    op_count = 4u + (size_t)(fuzz_cursor_take_u8(cursor, 0u) % 160u);
    for (i = 0u; i < op_count; ++i) {
        op = fuzz_cursor_take_u8(cursor, 0u);

        if (i > 1u && (op & 0x1fu) == 0u) {
            code = clear_code;
        } else if (i > 2u && (op & 0x3fu) == 1u) {
            code = eoi_code;
            saw_eoi = 1;
        } else if (prev_was_clear) {
            code_sample = fuzz_cursor_take_u16be(cursor, 0u);
            code = (uint16_t)(code_sample % clear_code);
        } else {
            upper = next_code;
            if (upper < clear_code) {
                upper = clear_code;
            }
            if (upper > 4095u) {
                upper = 4095u;
            }

            if ((op & 0x01u) == 0u) {
                code_sample = fuzz_cursor_take_u16be(cursor, 0u);
                code = (uint16_t)(code_sample % clear_code);
            } else {
                code_sample = fuzz_cursor_take_u16be(cursor, 0u);
                code = (uint16_t)(code_sample % (uint16_t)(upper + 1u));
            }
        }

        if (code == clear_code) {
            fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_CLEAR);
        } else if (code == eoi_code) {
            fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_EOI);
        } else if (code < clear_code) {
            fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_LITERAL);
        } else if (code > eoi_code) {
            fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_DICT);
        }

        if (!fuzz_gif_pack_code(stream,
                                &bit_acc,
                                &bit_count,
                                code,
                                code_size)) {
            return 0;
        }

        if (code == clear_code) {
            code_size = min_code_size + 1u;
            max_code_value = 1u << code_size;
            next_code = (uint16_t)(eoi_code + 1u);
            prev_was_clear = 1;
            continue;
        }

        if (code == eoi_code) {
            break;
        }

        if (!prev_was_clear) {
            if (next_code < 4095u) {
                ++next_code;
            }
            if ((unsigned int)next_code >= max_code_value && code_size < 12u) {
                ++code_size;
                max_code_value <<= 1u;
                fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_WIDTH_GROW);
            }
        }
        prev_was_clear = 0;
    }

    if (!saw_eoi) {
        if (!fuzz_gif_pack_code(stream,
                                &bit_acc,
                                &bit_count,
                                eoi_code,
                                code_size)) {
            return 0;
        }
        fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_EOI);
    }

    return fuzz_gif_flush_codes(stream, &bit_acc, &bit_count);
}

static int
fuzz_append_gif_subblocks_from_stream(fuzz_cursor_t *cursor,
                                      fuzz_byte_buffer_t *payload,
                                      fuzz_byte_buffer_t const *stream)
{
    size_t pos;
    size_t chunk_size;

    if (cursor == NULL || payload == NULL || stream == NULL) {
        return 0;
    }

    pos = 0u;
    while (pos < stream->size) {
        chunk_size = 1u + (size_t)(fuzz_cursor_take_u8(cursor, 0u) % 64u);
        if (chunk_size > stream->size - pos) {
            chunk_size = stream->size - pos;
        }
        fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_SUBBLOCK);
        if (chunk_size >= 32u) {
            fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_LONG_SUBBLOCK);
        }

        if (!fuzz_byte_buffer_append_u8(payload, (unsigned char)chunk_size) ||
            !fuzz_byte_buffer_append(payload,
                                     stream->data + pos,
                                     chunk_size)) {
            return 0;
        }
        pos += chunk_size;

        if (pos < stream->size &&
            (fuzz_cursor_take_u8(cursor, 0u) & 0x3fu) == 0u) {
            fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_EARLY_END);
            break;
        }
    }

    return fuzz_byte_buffer_append_u8(payload, 0u);
}

static int
fuzz_build_gif_lzw_codes_payload(uint8_t const *data,
                                 size_t size,
                                 fuzz_byte_buffer_t *payload)
{
    fuzz_cursor_t cursor;
    fuzz_byte_buffer_t stream;
    unsigned int min_code_size;
    uint16_t width;
    uint16_t height;
    uint16_t image_left;
    uint16_t image_top;
    unsigned int color_table_entries;
    unsigned char packed;
    unsigned char gce_packed;
    unsigned char image_packed;
    unsigned char red;
    unsigned char green;
    unsigned char blue;
    uint16_t gce_delay;
    unsigned int i;

    if (payload == NULL) {
        return 0;
    }

    fuzz_cursor_init(&cursor, data, size);
    fuzz_byte_buffer_init(&stream);

    min_code_size = 2u + (unsigned int)(fuzz_cursor_take_u8(&cursor, 0u) % 4u);
    color_table_entries = 1u << min_code_size;
    if (min_code_size >= 5u) {
        fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_LARGE_MIN_CODE);
    }

    width = (uint16_t)(1u + (fuzz_cursor_take_u8(&cursor, 0u) % 96u));
    height = (uint16_t)(1u + (fuzz_cursor_take_u8(&cursor, 0u) % 96u));
    packed = (unsigned char)(0x80u | 0x70u | ((min_code_size - 1u) & 0x07u));

    fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_HEADER);
    if (!fuzz_byte_buffer_append(payload,
                                 (unsigned char const *)"GIF89a",
                                 6u) ||
        !fuzz_byte_buffer_append_u16le(payload, width) ||
        !fuzz_byte_buffer_append_u16le(payload, height) ||
        !fuzz_byte_buffer_append_u8(payload, packed) ||
        !fuzz_byte_buffer_append_u8(payload, 0u) ||
        !fuzz_byte_buffer_append_u8(payload, 0u)) {
        fuzz_byte_buffer_reset(&stream);
        return 0;
    }

    for (i = 0u; i < color_table_entries; ++i) {
        red = fuzz_cursor_take_u8(&cursor, (unsigned char)(i & 0xffu));
        green = fuzz_cursor_take_u8(
            &cursor,
            (unsigned char)((i * 3u) & 0xffu));
        blue = fuzz_cursor_take_u8(
            &cursor,
            (unsigned char)((i * 5u) & 0xffu));
        if (!fuzz_byte_buffer_append_u8(payload, red) ||
            !fuzz_byte_buffer_append_u8(payload, green) ||
            !fuzz_byte_buffer_append_u8(payload, blue)) {
            fuzz_byte_buffer_reset(&stream);
            return 0;
        }
    }

    if ((fuzz_cursor_take_u8(&cursor, 0u) & 0x01u) != 0u) {
        gce_packed = (unsigned char)(fuzz_cursor_take_u8(&cursor, 0u) & 0x1fu);
        gce_delay = (uint16_t)fuzz_cursor_take_u16be(&cursor, 0u);
        fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_GCE);
        if ((gce_packed & 0x01u) != 0u) {
            fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_TRANSPARENT_GCE);
        }
        if (!fuzz_byte_buffer_append_u8(payload, 0x21u) ||
            !fuzz_byte_buffer_append_u8(payload, 0xf9u) ||
            !fuzz_byte_buffer_append_u8(payload, 4u) ||
            !fuzz_byte_buffer_append_u8(payload, gce_packed) ||
            !fuzz_byte_buffer_append_u16le(payload, gce_delay) ||
            !fuzz_byte_buffer_append_u8(payload,
                                        fuzz_cursor_take_u8(&cursor, 0u)) ||
            !fuzz_byte_buffer_append_u8(payload, 0u)) {
            fuzz_byte_buffer_reset(&stream);
            return 0;
        }
    }

    image_left = (uint16_t)(fuzz_cursor_take_u8(&cursor, 0u) % 8u);
    image_top = (uint16_t)(fuzz_cursor_take_u8(&cursor, 0u) % 8u);
    image_packed = (unsigned char)(fuzz_cursor_take_u8(&cursor, 0u) & 0x40u);
    if ((image_packed & 0x40u) != 0u) {
        fuzz_gif_lzw_note_feature(FUZZ_GIF_LZW_FEATURE_INTERLACE);
    }
    if (!fuzz_byte_buffer_append_u8(payload, 0x2cu) ||
        !fuzz_byte_buffer_append_u16le(payload, image_left) ||
        !fuzz_byte_buffer_append_u16le(payload, image_top) ||
        !fuzz_byte_buffer_append_u16le(payload, width) ||
        !fuzz_byte_buffer_append_u16le(payload, height) ||
        !fuzz_byte_buffer_append_u8(payload, image_packed) ||
        !fuzz_byte_buffer_append_u8(payload, (unsigned char)min_code_size)) {
        fuzz_byte_buffer_reset(&stream);
        return 0;
    }

    if (!fuzz_build_gif_lzw_stream(&cursor, min_code_size, &stream) ||
        !fuzz_append_gif_subblocks_from_stream(&cursor, payload, &stream) ||
        !fuzz_byte_buffer_append_u8(payload, 0x3bu)) {
        fuzz_byte_buffer_reset(&stream);
        return 0;
    }

    fuzz_byte_buffer_reset(&stream);
    return 1;
}

int
LLVMFuzzerInitialize(int *argc, char ***argv)
{
    (void)argc;
    (void)argv;
    fuzz_gif_lzw_register_semantic_stats();
    (void)fuzz_loader_builtin_runtime_bootstrap();
    return 0;
}

int
LLVMFuzzerTestOneInput(uint8_t const *data, size_t size)
{
    enum { FUZZ_MAX_INPUT_BYTES = 1 * 1024 * 1024 };

    fuzz_byte_buffer_t payload;

    if (data == NULL || size > (size_t)FUZZ_MAX_INPUT_BYTES) {
        return 0;
    }

    fuzz_gif_lzw_register_semantic_stats();
    fuzz_byte_buffer_init(&payload);
    if (!fuzz_build_gif_lzw_codes_payload(data, size, &payload)) {
        fuzz_byte_buffer_reset(&payload);
        return 0;
    }
    if (!fuzz_loader_builtin_runtime_bootstrap()) {
        fuzz_byte_buffer_reset(&payload);
        return 0;
    }

    (void)fuzz_loader_builtin_runtime_run(data,
                                          size,
                                          payload.data,
                                          payload.size);
    fuzz_byte_buffer_reset(&payload);
    return 0;
}

/* emacs Local Variables:      */
/* emacs mode: c               */
/* emacs tab-width: 4          */
/* emacs indent-tabs-mode: nil */
/* emacs c-basic-offset: 4     */
/* emacs End:                  */
/* vim: set expandtab ts=4 sts=4 sw=4 : */
/* EOF */
