#!/bin/sh -e

for a in "$@"; do
  if [ "$prev" = "-o" ]; then
    if [ "$a" = "sanitycheckc.exe" ]; then
      cp "$(which true)" "$a"
      exit 0
    fi
    out="$a"
  fi
  prev="$a"
done

emcc "$@"
ret=$?

if test "${out}" != "${bin:="${out%.js}"}"; then
  echo "${out} -> ${bin}" >&2
  #mkdir -pv "$(dirname "${bin}")"
  echo '#!/usr/bin/env node' > "${bin}"
  cat "${out}" >> "${bin}"
  chmod +x "${bin}"
fi

exit $ret
