#!/bin/sh
# Verify builtin loader decodes PSD RGB 32-bit Raw with stable image quality.
# Expected PPM is generated by ImageMagick from an equivalent 32-bit Raw PSD.

set -eux

test "${HAVE_IMG2SIXEL-}" = 1 || {
    printf "1..0 # SKIP img2sixel is disabled in this build\n"
    exit 0
}

. "${TOP_SRCDIR}/tests/_lib/sh/common.sh"

echo "1..1"
set -v
mkdir -p "${ARTIFACT_LOCAL_DIR}"

tmp_psd=$(mktemp "${TMPDIR:-/tmp}/libsixel-psd-rgb32-raw-XXXXXX.psd")
output_sixel="${ARTIFACT_LOCAL_DIR}/psd_rgb32_raw_output.six"
trap 'rm -f "${tmp_psd}"' EXIT HUP INT TERM

python3 - "${tmp_psd}" <<'PY'
import struct
import sys

out_psd = sys.argv[1]
width, height = 2, 2
channels = 3
mode = 3
depth = 32
compression = 0

planes = [
    [0.10, 0.20, 0.30, 0.40],
    [0.20, 0.30, 0.40, 0.50],
    [0.30, 0.40, 0.50, 0.60],
]
plane_bytes = []
for values in planes:
    b = bytearray()
    for v in values:
        b.extend(struct.pack(">f", float(v)))
    plane_bytes.append(bytes(b))

payload = b"".join(plane_bytes)

with open(out_psd, "wb") as f:
    f.write(b"8BPS")
    f.write(struct.pack(">H", 1))
    f.write(b"\x00" * 6)
    f.write(struct.pack(">H", channels))
    f.write(struct.pack(">I", height))
    f.write(struct.pack(">I", width))
    f.write(struct.pack(">H", depth))
    f.write(struct.pack(">H", mode))
    f.write(struct.pack(">I", 0))
    f.write(struct.pack(">I", 0))
    f.write(struct.pack(">I", 0))
    f.write(struct.pack(">H", compression))
    f.write(payload)
PY

lsqa_floor=${LSQA_MS_SSIM_FLOOR:-0.995}
reference_ppm="${TOP_SRCDIR}/tests/data/loader/builtin_expected/psd_rgb32_raw_expected.ppm"

run_img2sixel -L builtin! "${tmp_psd}" >"${output_sixel}" || {
    echo "not ok" 1 - "PSD RGB 32-bit Raw decode failed"
    exit 0
}

lsqa_msg=$(set +xv; run_lsqa -m MS-SSIM -b "MS-SSIM:${lsqa_floor}" \
    "${reference_ppm}" "${output_sixel}" 2>&1) || {
    echo "not ok" 1 - "PSD RGB 32-bit Raw fell below MS-SSIM ${lsqa_floor}: ${lsqa_msg}"
    exit 0
}

echo "ok" 1 - "PSD RGB 32-bit Raw keeps MS-SSIM ${lsqa_floor} against expected PPM"
exit 0
