/*
 * SPDX-License-Identifier: MIT
 *
 * Copyright (c) 2026 libsixel developers. See `AUTHORS`.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*
 * Auto-generated by tools/gen_6cells_h.awk from include/6cells.idl;
 * do not edit include/6cells.h directly.
 */

#ifndef LIBSIXEL_6CELLS_H
#define LIBSIXEL_6CELLS_H

#include <stddef.h>

#include <sixel.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Attribute contract:
 *
 * [component]
 * - Marks an interface as a 6cells component boundary.  Concrete storage stays
 *   hidden, and callers operate through the generated vtbl contract.
 *
 * [native]
 * - Marks a C-native primitive or handle that participates in the 6cells
 *   contract without becoming an interface or factory-created component.
 *
 * [opaque]
 * - Marks a native type whose concrete storage stays hidden outside its owning
 *   implementation.
 *
 * [refcounted]
 * - Marks a component or native type whose lifetime is controlled by
 *   ref()/unref().
 *
 * [responsibility("...")]
 * - Records the component's single responsibility in machine-readable form.
 *
 * [forbid_state("name", ...)]
 * - Lists state categories that must not be owned by the component.  The
 *   generator expands each state name into the generated header comment.
 *
 * [classid("...")]
 * - Applies to coclass declarations only and records the factory lookup key.
 *
 * [serviceid("...")]
 * - Applies to service interfaces and records the service lookup key.
 *
 * [lifetime(retained)] / [lifetime(release)]
 * - Marks refcount operations that retain or release the receiver.
 *
 * [mutates]
 * - Marks a method that changes receiver-owned state.
 *
 * [invalidates(name, ...)]
 * - Lists borrowed views or pointers invalidated by a mutating method.
 *
 * [borrows(name)]
 * - Marks a returned pointer or out view as borrowed from the receiver.  The
 *   caller must not free it.  Borrowed values become invalid after unref() or
 *   after a method whose [invalidates(...)] list contains the same name.
 *
 * [const]
 * - Marks a method whose generated receiver argument is const-qualified.
 *
 * [alias(...)] / [receiver(...)]
 * - Control C projection names only; they are not semantic design contracts.
 *
 * coclass name { [default] interface iface; };
 * - Records that a factory-created concrete component provides iface.  The
 *   syntax intentionally follows COM/MIDL-style coclass blocks.
 */
/*
 * Component services expose stable interface objects without exposing their
 * concrete storage.  Callers that need post-v1.8.7 component contracts should
 * include this header explicitly; sixel.h stays focused on the legacy public
 * API surface.
 */
struct sixel_option_argument_list_resolution;
/*
 * IDL responsibility:
 * - provide allocation services required by factory creation
 */

/*
 * IDL contract:
 * [native, opaque, refcounted]
 * [responsibility("provide allocation services required by factory creation")]
 * typedef sixel_allocator_t allocator;
 */

typedef struct sixel_timeline_logger_interface sixel_timeline_logger_t;

typedef struct sixel_timeline_event {
    char const *role;
    char const *worker;
    char const *event;
    int job_id;
} sixel_timeline_event_t;

typedef struct sixel_timeline_frame_context {
    int frame_no;
    int loop_no;
    int multiframe;
} sixel_timeline_frame_context_t;

typedef struct sixel_timeline_record {
    unsigned int session_id;
    double timestamp;
    unsigned long long thread_id;
    char const *worker;
    char const *role;
    char const *event;
    int job_id;
    int frame_no;
    int loop_no;
    int multiframe;
} sixel_timeline_record_t;

typedef struct sixel_timeline_writer_interface sixel_timeline_writer_t;

/*
 * IDL responsibility:
 * - own shared diagnostic timeline JSONL output and clock origin
 */

/*
 * IDL forbidden state:
 * - frame_context
 * - job_context
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [serviceid("services/timeline-writer")]
 * [responsibility("own shared diagnostic timeline JSONL output and clock origin")]
 * [forbid_state("frame_context", "job_context")]
 * [alias(sixel_timeline_writer_t)]
 * [receiver(writer)]
 * interface timeline_writer {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     SIXELSTATUS create_logger(
 *         in allocator *allocator,
 *         out timeline_logger **logger);
 *     SIXELSTATUS write(in timeline_record const *record);
 *     void flush();
 * };
 */

typedef struct sixel_timeline_writer_vtbl {
    void (*ref)(sixel_timeline_writer_t *writer);
    void (*unref)(sixel_timeline_writer_t *writer);
    SIXELSTATUS (*create_logger)(
        sixel_timeline_writer_t *writer,
        sixel_allocator_t *allocator,
        sixel_timeline_logger_t **logger);
    SIXELSTATUS (*write)(
        sixel_timeline_writer_t *writer,
        sixel_timeline_record_t const *record);
    void (*flush)(sixel_timeline_writer_t *writer);
} sixel_timeline_writer_vtbl_t;

struct sixel_timeline_writer_interface {
    sixel_timeline_writer_vtbl_t const *vtbl;
};

/*
 * TODO: Replace ambient frame context with an explicit event/context DTO
 * so frame scope is not hidden mutable state on timeline_logger.
 */
/*
 * IDL responsibility:
 * - record one diagnostic timeline session
 */

/*
 * IDL forbidden state:
 * - output_file
 * - global_writer
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("record one diagnostic timeline session")]
 * [forbid_state("output_file", "global_writer")]
 * [receiver(logger)]
 * interface timeline_logger {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     SIXELSTATUS log(in timeline_event const *event);
 *     SIXELSTATUS set_frame_context(
 *         in timeline_frame_context const *context);
 *     void clear_frame_context();
 *     [const] unsigned int session_id();
 * };
 */

typedef struct sixel_timeline_logger_vtbl {
    void (*ref)(sixel_timeline_logger_t *logger);
    void (*unref)(sixel_timeline_logger_t *logger);
    SIXELSTATUS (*log)(
        sixel_timeline_logger_t *logger,
        sixel_timeline_event_t const *event);
    SIXELSTATUS (*set_frame_context)(
        sixel_timeline_logger_t *logger,
        sixel_timeline_frame_context_t const *context);
    void (*clear_frame_context)(sixel_timeline_logger_t *logger);
    unsigned int (*session_id)(sixel_timeline_logger_t const *logger);
} sixel_timeline_logger_vtbl_t;

struct sixel_timeline_logger_interface {
    sixel_timeline_logger_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("diagnostics/timeline-logger")]
 * coclass timeline_logger_component {
 *     [default] interface timeline_logger;
 * };
 */

typedef struct sixel_factory_interface sixel_factory_t;

/*
 * IDL responsibility:
 * - create components by class id
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("create components by class id")]
 * [alias(sixel_factory_t)]
 * interface factory {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     SIXELSTATUS create(
 *         in char const *class_name,
 *         in allocator *allocator,
 *         out void **object);
 * };
 */

typedef struct sixel_factory_vtbl {
    void (*ref)(sixel_factory_t *factory);
    void (*unref)(sixel_factory_t *factory);
    SIXELSTATUS (*create)(
        sixel_factory_t *factory,
        char const *class_name,
        sixel_allocator_t *allocator,
        void **object);
} sixel_factory_vtbl_t;

struct sixel_factory_interface {
    sixel_factory_vtbl_t const *vtbl;
};

/*
 * getservice("services/factory", &factory) returns the process-wide factory
 * service with interface-level ownership.  Release it with factory->vtbl->unref
 * when the caller is done with the service pointer.
 */
SIXELAPI SIXELSTATUS
sixel_components_getservice(char const *name,
    void **service);

/*
 * Ownership/lifetime:
 * - Factory create returns refcount=1 policy objects.
 * - Callers release with policy->vtbl->unref(policy).
 *
 * Creation path:
 * - sixel_lookup_policy_select_name(select_request)
 * - services/factory -> create("lookup/...", allocator, &policy)
 * - factory resolves class ids via generated classid registry
 * - policy->prepare(request)
 *
 * Reuse path:
 * - Callers may pass a prepared policy object through
 *   request.reuse_policy/request.reuse_policy_slot.
 * - request.parallel_dither_active carries execution context so policies can
 *   disable non-thread-safe cache paths without relying on global state.
 * - request.shared_instance_enabled stores the effective shared-instance
 *   preference resolved by the caller (CLI override or environment default).
 * - Implementations may choose to ignore reuse hints.
 */
typedef struct sixel_lookup_policy_interface sixel_lookup_policy_interface_t;

typedef struct sixel_lookup_policy_select_request {
    unsigned char const *palette;
    int depth;
    int reqcolor;
    int optimize_lookup;
    int lut_policy;
    int pixelformat;
} sixel_lookup_policy_select_request_t;

typedef struct sixel_lookup_policy_prepare_request {
    unsigned char const *palette;
    float const *palette_float;
    int depth;
    int float_depth;
    int reqcolor;
    int pixelformat;
    int parallel_dither_active;
    int shared_instance_enabled;
    sixel_lookup_policy_interface_t *reuse_policy;
    sixel_lookup_policy_interface_t **reuse_policy_slot;
    sixel_allocator_t *allocator;
} sixel_lookup_policy_prepare_request_t;

typedef int sixel_lookup_policy_result_t;

/*
 * IDL responsibility:
 * - map pixels to palette indexes
 */

/*
 * IDL forbidden state:
 * - image_pixels
 * - output_pixels
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("map pixels to palette indexes")]
 * [forbid_state("image_pixels", "output_pixels")]
 * [receiver(policy)]
 * interface lookup_policy {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates]
 *     SIXELSTATUS prepare(in lookup_policy_prepare_request const *request);
 *     [const] lookup_policy_result map_pixel(
 *         in unsigned char const *pixel);
 * };
 */

typedef struct sixel_lookup_policy_vtbl {
    void (*ref)(sixel_lookup_policy_interface_t *policy);
    void (*unref)(sixel_lookup_policy_interface_t *policy);
    SIXELSTATUS (*prepare)(
        sixel_lookup_policy_interface_t *policy,
        sixel_lookup_policy_prepare_request_t const *request);
    sixel_lookup_policy_result_t (*map_pixel)(
        sixel_lookup_policy_interface_t const *policy,
        unsigned char const *pixel);
} sixel_lookup_policy_vtbl_t;

struct sixel_lookup_policy_interface {
    sixel_lookup_policy_vtbl_t const *vtbl;
};

/*
 * Ownership/lifetime:
 * - Factory create returns refcount=1 policy objects.
 * - Callers release with policy->vtbl->unref(policy).
 *
 * Creation path:
 * - sixel_dither_policy_select_name(select_request)
 * - services/factory -> create("dither/...", allocator, &policy)
 * - policy->prepare(request)
 */
typedef struct sixel_dither_policy_interface sixel_dither_policy_interface_t;

typedef struct sixel_dither_policy_select_request {
    int method_for_diffuse;
    int ncolors;
    int pixelformat;
} sixel_dither_policy_select_request_t;

typedef struct sixel_dither_policy_prepare_request {
    sixel_dither_t *dither;
    int depth;
    int method_for_scan;
    int pixelformat;
} sixel_dither_policy_prepare_request_t;

typedef struct sixel_dither_policy_apply_request {
    sixel_index_t *result;
    unsigned char *data;
    int width;
    int height;
    int band_origin;
    int output_start;
    int depth;
    unsigned char *palette;
    int method_for_scan;
    sixel_lookup_policy_interface_t *lookup_policy;
    sixel_dither_t *dither;
    int pixelformat;
} sixel_dither_policy_apply_request_t;

typedef int sixel_dither_policy_supports_parallel_result_t;

/*
 * IDL responsibility:
 * - apply dithering from pixels and lookup policy
 */

/*
 * IDL forbidden state:
 * - input_owner
 * - output_owner
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("apply dithering from pixels and lookup policy")]
 * [forbid_state("input_owner", "output_owner")]
 * [receiver(policy)]
 * interface dither_policy {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates]
 *     SIXELSTATUS prepare(in dither_policy_prepare_request const *request);
 *     SIXELSTATUS apply(in dither_policy_apply_request const *request);
 *     [const] dither_policy_supports_parallel_result supports_parallel_bands();
 * };
 */

typedef struct sixel_dither_policy_vtbl {
    void (*ref)(sixel_dither_policy_interface_t *policy);
    void (*unref)(sixel_dither_policy_interface_t *policy);
    SIXELSTATUS (*prepare)(
        sixel_dither_policy_interface_t *policy,
        sixel_dither_policy_prepare_request_t const *request);
    SIXELSTATUS (*apply)(
        sixel_dither_policy_interface_t *policy,
        sixel_dither_policy_apply_request_t const *request);
    sixel_dither_policy_supports_parallel_result_t
    (*supports_parallel_bands)(
        sixel_dither_policy_interface_t const *policy);
} sixel_dither_policy_vtbl_t;

struct sixel_dither_policy_interface {
    sixel_dither_policy_vtbl_t const *vtbl;
};

typedef struct sixel_chunk_interface sixel_chunk_t;

typedef struct sixel_chunk_source_request {
    char const *filename;
    int finsecure;
    int const *cancel_flag;
} sixel_chunk_source_request_t;

typedef struct sixel_chunk_memory_request {
    unsigned char const *bytes;
    size_t size;
    char const *source_path;
} sixel_chunk_memory_request_t;

typedef struct sixel_chunk_bytes_view {
    unsigned char const *bytes;
    size_t size;
} sixel_chunk_bytes_view_t;

/*
 * Ownership/lifetime:
 * - Factory create returns refcount=1 chunk objects.
 * - Callers release with chunk->vtbl->unref(chunk).
 *
 * Encapsulation path:
 * - The chunk object owns loaded input bytes and optional source metadata.
 * - Loaders keep their own decode cursors; chunk bytes are read-only views.
 */
/*
 * IDL responsibility:
 * - own input bytes and source metadata only
 */

/*
 * IDL forbidden state:
 * - read_cursor
 * - decode_state
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("own input bytes and source metadata only")]
 * [forbid_state("read_cursor", "decode_state")]
 * [receiver(chunk)]
 * interface chunk {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates, invalidates(bytes_view, source_path)]
 *     SIXELSTATUS init_source(in chunk_source_request const *request);
 *     [mutates, invalidates(bytes_view, source_path)]
 *     SIXELSTATUS init_memory(in chunk_memory_request const *request);
 *     [const, borrows(bytes_view)]
 *     SIXELSTATUS get_bytes(out chunk_bytes_view *view);
 *     [const, borrows(source_path)]
 *     char const *source_path();
 *     [const, borrows(allocator)]
 *     allocator *allocator();
 * };
 */

typedef struct sixel_chunk_vtbl {
    void (*ref)(sixel_chunk_t *chunk);
    void (*unref)(sixel_chunk_t *chunk);
    SIXELSTATUS (*init_source)(
        sixel_chunk_t *chunk,
        sixel_chunk_source_request_t const *request);
    SIXELSTATUS (*init_memory)(
        sixel_chunk_t *chunk,
        sixel_chunk_memory_request_t const *request);
    SIXELSTATUS (*get_bytes)(
        sixel_chunk_t const *chunk,
        sixel_chunk_bytes_view_t *view);
    char const *(*source_path)(sixel_chunk_t const *chunk);
    sixel_allocator_t *(*allocator)(sixel_chunk_t const *chunk);
} sixel_chunk_vtbl_t;

struct sixel_chunk_interface {
    sixel_chunk_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("image/chunk")]
 * coclass chunk_component {
 *     [default] interface chunk;
 * };
 */

typedef struct sixel_loader_component_interface
    sixel_loader_component_interface_t;

/*
 * IDL responsibility:
 * - decode one chunk through one loader backend
 */

/*
 * IDL forbidden state:
 * - loader_chain
 * - global_decode_cursor
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("decode one chunk through one loader backend")]
 * [forbid_state("loader_chain", "global_decode_cursor")]
 * [receiver(loader)]
 * interface loader_component {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates]
 *     SIXELSTATUS setopt(in int option, in void const *value);
 *     SIXELSTATUS load(
 *         in chunk const *chunk,
 *         in sixel_load_image_function fn_load,
 *         in void *context);
 *     [const] char const *name();
 *     int predicate(in chunk const *chunk);
 * };
 */

typedef struct sixel_loader_component_vtbl {
    void (*ref)(sixel_loader_component_interface_t *loader);
    void (*unref)(sixel_loader_component_interface_t *loader);
    SIXELSTATUS (*setopt)(
        sixel_loader_component_interface_t *loader,
        int option,
        void const *value);
    SIXELSTATUS (*load)(
        sixel_loader_component_interface_t *loader,
        sixel_chunk_t const *chunk,
        sixel_load_image_function fn_load,
        void *context);
    char const *(*name)(sixel_loader_component_interface_t const *loader);
    int (*predicate)(
        sixel_loader_component_interface_t *loader,
        sixel_chunk_t const *chunk);
} sixel_loader_component_vtbl_t;

struct sixel_loader_component_interface {
    sixel_loader_component_vtbl_t const *vtbl;
};

typedef sixel_loader_component_interface_t sixel_loader_component_t;

typedef sixel_loader_component_vtbl_t sixel_loader_vtbl_t;

typedef struct sixel_loader_manager_interface sixel_loader_manager_t;

typedef struct sixel_loader_suboptions {
    int wic_ico_minsize;
    int libjpeg_enable_cms;
    int libjpeg_cms_engine;
    int libjpeg_enable_orientation;
    int libpng_enable_cms;
    int libpng_cms_engine;
    int libpng_enable_orientation;
    int libwebp_enable_cms;
    int libwebp_cms_engine;
    int libwebp_enable_orientation;
    int coregraphics_enable_orientation;
    int libtiff_enable_cms;
    int libtiff_cms_engine;
    int builtin_enable_cms;
    int builtin_cms_engine;
    int builtin_enable_orientation;
    int builtin_bmp_info40_mode;
} sixel_loader_suboptions_t;

typedef struct sixel_loader_manager_build_request {
    struct sixel_option_argument_list_resolution const *resolution;
    int skip_predicate_gate;
    int require_static;
    int use_palette;
    int reqcolors;
    unsigned char const *bgcolor;
    int has_bgcolor;
    int bgcolor_source;
    int loop_control;
    int has_start_frame_no;
    int start_frame_no;
    sixel_loader_suboptions_t const *suboptions;
    sixel_timeline_logger_t *timeline_logger;
    int *timeline_job_seq;
    sixel_loader_t *timeline_loader;
} sixel_loader_manager_build_request_t;

/*
 * IDL responsibility:
 * - build loader chains and select loaders for chunks
 */

/*
 * IDL forbidden state:
 * - chunk_bytes
 * - pixel_storage
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("build loader chains and select loaders for chunks")]
 * [forbid_state("chunk_bytes", "pixel_storage")]
 * [receiver(manager)]
 * interface loader_manager {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates, invalidates(loader_chain, selected_loader)]
 *     SIXELSTATUS build_chain(in loader_manager_build_request const *request);
 *     [borrows(selected_loader)]
 *     SIXELSTATUS load(
 *         in chunk const *chunk,
 *         out loader_component **selected_loader,
 *         in sixel_load_image_function fn_load,
 *         in void *load_context);
 * };
 */

typedef struct sixel_loader_manager_vtbl {
    void (*ref)(sixel_loader_manager_t *manager);
    void (*unref)(sixel_loader_manager_t *manager);
    SIXELSTATUS (*build_chain)(
        sixel_loader_manager_t *manager,
        sixel_loader_manager_build_request_t const *request);
    SIXELSTATUS (*load)(
        sixel_loader_manager_t *manager,
        sixel_chunk_t const *chunk,
        sixel_loader_component_interface_t **selected_loader,
        sixel_load_image_function fn_load,
        void *load_context);
} sixel_loader_manager_vtbl_t;

struct sixel_loader_manager_interface {
    sixel_loader_manager_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("loader/manager")]
 * coclass loader_manager_component {
 *     [default] interface loader_manager;
 * };
 */

/*
 * Ownership/lifetime:
 * - Existing public sixel_frame_new() returns refcount=1 frame objects.
 * - init_pixels() takes ownership of request->pixels and request->palette,
 *   matching sixel_frame_init().
 * - set_transparency() takes ownership of request->transparent_mask.
 *
 * Encapsulation path:
 * - This header exposes only the object contract and request/view DTOs.
 * - src/frame-private.h remains a temporary storage owner while loader-side
 *   direct-field callers migrate toward this interface.
 * - src/frame.c owns frame operations that need concrete storage access.
 */
typedef struct sixel_frame_interface sixel_frame_interface_t;

typedef enum sixel_frame_pixels_kind {
    SIXEL_FRAME_PIXELS_U8 = 0,
    SIXEL_FRAME_PIXELS_FLOAT32 = 1
} sixel_frame_pixels_kind_t;

typedef struct sixel_frame_pixels_request {
    void *pixels;
    unsigned char *palette;
    int width;
    int height;
    int pixelformat;
    int colorspace; /* negative means infer from pixelformat */
    int ncolors;
    sixel_frame_pixels_kind_t kind;
} sixel_frame_pixels_request_t;

typedef struct sixel_frame_pixels_view {
    unsigned char *pixels;
    float *pixels_float32;
    unsigned char *palette;
    int width;
    int height;
    int pixelformat;
    int colorspace;
    int ncolors;
} sixel_frame_pixels_view_t;

typedef struct sixel_frame_timeline {
    int delay;
    int frame_no;
    int loop_count;
    int multiframe;
    int handoff_shareable;
} sixel_frame_timeline_t;

typedef struct sixel_frame_transparency {
    int transparent;
    int alpha_zero_is_transparent;
    unsigned char *transparent_mask;
    size_t transparent_mask_size;
} sixel_frame_transparency_t;

/*
 * IDL responsibility:
 * - own pixel storage and per-frame metadata
 */

/*
 * IDL forbidden state:
 * - lookup_policy
 * - dither_policy
 * - decode_state
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("own pixel storage and per-frame metadata")]
 * [forbid_state("lookup_policy", "dither_policy", "decode_state")]
 * interface frame {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS init_pixels(in frame_pixels_request const *request);
 *     [borrows(pixels_view)]
 *     SIXELSTATUS get_pixels(out frame_pixels_view *view);
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS set_pixelformat(in int pixelformat);
 *     SIXELSTATUS get_timeline(out frame_timeline *timeline);
 *     [mutates]
 *     SIXELSTATUS set_timeline(in frame_timeline const *timeline);
 *     SIXELSTATUS get_transparency(out frame_transparency *transparency);
 *     [mutates]
 *     SIXELSTATUS set_transparency(in frame_transparency const *transparency);
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS resize(
 *         in int width,
 *         in int height,
 *         in int method_for_resampling);
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS resize_float32(
 *         in int width,
 *         in int height,
 *         in int method_for_resampling);
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS clip(in int x, in int y, in int width, in int height);
 *     [borrows(allocator)]
 *     allocator *allocator();
 *     SIXELSTATUS measure_storage(out size_t *storage_bytes);
 *     SIXELSTATUS clone(
 *         in allocator *allocator,
 *         out frame **frame_out);
 * };
 */

typedef struct sixel_frame_vtbl {
    void (*ref)(sixel_frame_interface_t *frame);
    void (*unref)(sixel_frame_interface_t *frame);
    SIXELSTATUS (*init_pixels)(
        sixel_frame_interface_t *frame,
        sixel_frame_pixels_request_t const *request);
    SIXELSTATUS (*get_pixels)(
        sixel_frame_interface_t *frame,
        sixel_frame_pixels_view_t *view);
    SIXELSTATUS (*set_pixelformat)(
        sixel_frame_interface_t *frame,
        int pixelformat);
    SIXELSTATUS (*get_timeline)(
        sixel_frame_interface_t *frame,
        sixel_frame_timeline_t *timeline);
    SIXELSTATUS (*set_timeline)(
        sixel_frame_interface_t *frame,
        sixel_frame_timeline_t const *timeline);
    SIXELSTATUS (*get_transparency)(
        sixel_frame_interface_t *frame,
        sixel_frame_transparency_t *transparency);
    SIXELSTATUS (*set_transparency)(
        sixel_frame_interface_t *frame,
        sixel_frame_transparency_t const *transparency);
    SIXELSTATUS (*resize)(
        sixel_frame_interface_t *frame,
        int width,
        int height,
        int method_for_resampling);
    SIXELSTATUS (*resize_float32)(
        sixel_frame_interface_t *frame,
        int width,
        int height,
        int method_for_resampling);
    SIXELSTATUS (*clip)(
        sixel_frame_interface_t *frame,
        int x,
        int y,
        int width,
        int height);
    sixel_allocator_t *(*allocator)(sixel_frame_interface_t *frame);
    SIXELSTATUS (*measure_storage)(
        sixel_frame_interface_t *frame,
        size_t *storage_bytes);
    SIXELSTATUS (*clone)(
        sixel_frame_interface_t *frame,
        sixel_allocator_t *allocator,
        sixel_frame_interface_t **frame_out);
} sixel_frame_vtbl_t;

struct sixel_frame_interface {
    sixel_frame_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("image/frame")]
 * coclass frame_component {
 *     [default] interface frame;
 * };
 */

static inline sixel_frame_interface_t *
sixel_frame_as_interface(sixel_frame_t const *frame)
{
    return (sixel_frame_interface_t *)frame;
}

#ifdef __cplusplus
}
#endif

#endif /* LIBSIXEL_6CELLS_H */

/* emacs Local Variables:      */
/* emacs mode: c               */
/* emacs tab-width: 4          */
/* emacs indent-tabs-mode: nil */
/* emacs c-basic-offset: 4     */
/* emacs End:                  */
/* vim: set expandtab ts=4 sts=4 sw=4 : */
/* EOF */
