/*
 * SPDX-License-Identifier: MIT
 *
 * Copyright (c) 2026 libsixel developers. See `AUTHORS`.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*
 * Auto-generated by tools/gen_6cells_h.awk from include/6cells.idl;
 * do not edit include/6cells.h directly.
 */

#ifndef LIBSIXEL_6CELLS_H
#define LIBSIXEL_6CELLS_H

#include <stddef.h>

#include <sixel.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Attribute contract:
 *
 * [component]
 * - Marks an interface as a 6cells component boundary.  Concrete storage stays
 *   hidden, and callers operate through the generated vtbl contract.
 *
 * [native]
 * - Marks a C-native primitive or handle that participates in the 6cells
 *   contract without becoming an interface or factory-created component.
 *
 * [opaque]
 * - Marks a native type whose concrete storage stays hidden outside its owning
 *   implementation.
 *
 * [refcounted]
 * - Marks a component or native type whose lifetime is controlled by
 *   ref()/unref().
 *
 * [responsibility("...")]
 * - Records the component's single responsibility in machine-readable form.
 *
 * [forbid_state("name", ...)]
 * - Lists state categories that must not be owned by the component.  The
 *   generator expands each state name into the generated header comment.
 *
 * [classid("...")]
 * - Applies to coclass declarations only and records the factory lookup key.
 *
 * [serviceid("...")]
 * - Applies to coclass declarations only and records the service lookup key.
 *
 * [lifetime(retained)] / [lifetime(release)]
 * - Marks refcount operations that retain or release the receiver.
 *
 * [mutates]
 * - Marks a method that changes receiver-owned state.
 *
 * [invalidates(name, ...)]
 * - Lists borrowed views or pointers invalidated by a mutating method.
 *
 * [borrows(name)]
 * - Marks a returned pointer or out view as borrowed from the receiver.  The
 *   caller must not free it.  Borrowed values become invalid after unref() or
 *   after a method whose [invalidates(...)] list contains the same name.
 *
 * [const]
 * - Marks a method whose generated receiver argument is const-qualified.
 *
 * [alias(...)]
 * - Controls C projection type names only; it is not a semantic design
 *   contract.  Generated vtbl receiver arguments are always named self.
 *
 * coclass name { [default] interface iface; };
 * - Records that a factory-created concrete component provides iface.  The
 *   syntax intentionally follows COM/MIDL-style coclass blocks.
 */
/*
 * Component services expose stable interface objects without exposing their
 * concrete storage.  Callers that need post-v1.8.7 component contracts should
 * include this header explicitly; sixel.h stays focused on the legacy public
 * API surface.
 */
struct sixel_option_argument_list_resolution;
/*
 * IDL responsibility:
 * - provide allocation services required by factory creation
 */

/*
 * IDL contract:
 * [native, opaque, refcounted]
 * [responsibility("provide allocation services required by factory creation")]
 * typedef sixel_allocator_t allocator;
 */

typedef struct sixel_timeline_logger_interface sixel_timeline_logger_t;

typedef struct sixel_timeline_event {
    char const *role;
    char const *worker;
    char const *event;
    int job_id;
} sixel_timeline_event_t;

typedef struct sixel_timeline_frame_context {
    int frame_no;
    int loop_no;
    int multiframe;
} sixel_timeline_frame_context_t;

typedef struct sixel_timeline_record {
    unsigned int session_id;
    double timestamp;
    unsigned long long thread_id;
    char const *worker;
    char const *role;
    char const *event;
    int job_id;
    int frame_no;
    int loop_no;
    int multiframe;
} sixel_timeline_record_t;

typedef struct sixel_timeline_writer_interface sixel_timeline_writer_t;

/*
 * IDL responsibility:
 * - own shared diagnostic timeline JSONL output and clock origin
 */

/*
 * IDL forbidden state:
 * - frame_context
 * - job_context
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("own shared diagnostic timeline JSONL output and clock origin")]
 * [forbid_state("frame_context", "job_context")]
 * [alias(sixel_timeline_writer_t)]
 * interface timeline_writer {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     SIXELSTATUS create_logger(
 *         in allocator *allocator,
 *         out timeline_logger **logger);
 *     SIXELSTATUS write(in timeline_record const *record);
 *     void flush();
 * };
 */

typedef struct sixel_timeline_writer_vtbl {
    void (*ref)(sixel_timeline_writer_t *self);
    void (*unref)(sixel_timeline_writer_t *self);
    SIXELSTATUS (*create_logger)(
        sixel_timeline_writer_t *self,
        sixel_allocator_t *allocator,
        sixel_timeline_logger_t **logger);
    SIXELSTATUS (*write)(
        sixel_timeline_writer_t *self,
        sixel_timeline_record_t const *record);
    void (*flush)(sixel_timeline_writer_t *self);
} sixel_timeline_writer_vtbl_t;

struct sixel_timeline_writer_interface {
    sixel_timeline_writer_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [serviceid("services/timeline-writer")]
 * coclass timeline_writer_component {
 *     [default] interface timeline_writer;
 * };
 */

/*
 * TODO: Replace ambient frame context with an explicit event/context DTO
 * so frame scope is not hidden mutable state on timeline_logger.
 */
/*
 * IDL responsibility:
 * - record one diagnostic timeline session
 */

/*
 * IDL forbidden state:
 * - output_file
 * - global_writer
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("record one diagnostic timeline session")]
 * [forbid_state("output_file", "global_writer")]
 * interface timeline_logger {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     SIXELSTATUS log(in timeline_event const *event);
 *     SIXELSTATUS set_frame_context(
 *         in timeline_frame_context const *context);
 *     void clear_frame_context();
 *     [const] unsigned int session_id();
 * };
 */

typedef struct sixel_timeline_logger_vtbl {
    void (*ref)(sixel_timeline_logger_t *self);
    void (*unref)(sixel_timeline_logger_t *self);
    SIXELSTATUS (*log)(
        sixel_timeline_logger_t *self,
        sixel_timeline_event_t const *event);
    SIXELSTATUS (*set_frame_context)(
        sixel_timeline_logger_t *self,
        sixel_timeline_frame_context_t const *context);
    void (*clear_frame_context)(sixel_timeline_logger_t *self);
    unsigned int (*session_id)(sixel_timeline_logger_t const *self);
} sixel_timeline_logger_vtbl_t;

struct sixel_timeline_logger_interface {
    sixel_timeline_logger_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("diagnostics/timeline-logger")]
 * coclass timeline_logger_component {
 *     [default] interface timeline_logger;
 * };
 */

typedef struct sixel_thread_pool_job {
    int band_index;
} sixel_thread_pool_job_t;

typedef int (*sixel_thread_pool_worker_function_t)(
    sixel_thread_pool_job_t job,
    void *userdata,
    void *workspace);

typedef void (*sixel_thread_pool_workspace_cleanup_function_t)(
    void *workspace);

typedef struct sixel_thread_pool_interface sixel_thread_pool_t;

typedef struct sixel_thread_pool_create_request {
    int threads;
    int queue_size;
    size_t workspace_size;
    sixel_thread_pool_worker_function_t worker;
    void *userdata;
    sixel_thread_pool_workspace_cleanup_function_t workspace_cleanup;
} sixel_thread_pool_create_request_t;

/*
 * IDL responsibility:
 * - own one short-lived worker queue and its worker threads
 */

/*
 * IDL forbidden state:
 * - global_queue
 * - process_thread_budget
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("own one short-lived worker queue and its worker threads")]
 * [forbid_state("global_queue", "process_thread_budget")]
 * interface thread_pool {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates]
 *     void set_affinity(in int pin_threads);
 *     [mutates]
 *     SIXELSTATUS push(in thread_pool_job job);
 *     [mutates]
 *     void finish();
 *     int get_error();
 *     [mutates]
 *     SIXELSTATUS grow(in int additional_threads);
 * };
 */

typedef struct sixel_thread_pool_vtbl {
    void (*ref)(sixel_thread_pool_t *self);
    void (*unref)(sixel_thread_pool_t *self);
    void (*set_affinity)(
        sixel_thread_pool_t *self,
        int pin_threads);
    SIXELSTATUS (*push)(
        sixel_thread_pool_t *self,
        sixel_thread_pool_job_t job);
    void (*finish)(sixel_thread_pool_t *self);
    int (*get_error)(sixel_thread_pool_t *self);
    SIXELSTATUS (*grow)(
        sixel_thread_pool_t *self,
        int additional_threads);
} sixel_thread_pool_vtbl_t;

struct sixel_thread_pool_interface {
    sixel_thread_pool_vtbl_t const *vtbl;
};

typedef struct sixel_threadpool_service_interface sixel_threadpool_service_t;

/*
 * IDL responsibility:
 * - create independent thread pools and resolve thread counts
 */

/*
 * IDL forbidden state:
 * - worker_threads
 * - job_queue
 * - encoder_state
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("create independent thread pools and resolve thread counts")]
 * [forbid_state("worker_threads", "job_queue", "encoder_state")]
 * [alias(sixel_threadpool_service_t)]
 * interface threadpool_service {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     int resolve_threads(in int requested);
 *     SIXELSTATUS create_pool(
 *         in thread_pool_create_request const *request,
 *         out thread_pool **pool);
 * };
 */

typedef struct sixel_threadpool_service_vtbl {
    void (*ref)(sixel_threadpool_service_t *self);
    void (*unref)(sixel_threadpool_service_t *self);
    int (*resolve_threads)(
        sixel_threadpool_service_t *self,
        int requested);
    SIXELSTATUS (*create_pool)(
        sixel_threadpool_service_t *self,
        sixel_thread_pool_create_request_t const *request,
        sixel_thread_pool_t **pool);
} sixel_threadpool_service_vtbl_t;

struct sixel_threadpool_service_interface {
    sixel_threadpool_service_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [serviceid("services/threadpool")]
 * coclass threadpool_service_component {
 *     [default] interface threadpool_service;
 * };
 */

typedef struct sixel_encoder_core_interface sixel_encoder_core_t;

typedef struct sixel_writer_interface sixel_writer_t;

typedef struct sixel_writer_init_request {
    sixel_write_function fn_write;
    void *priv;
} sixel_writer_init_request_t;

typedef struct sixel_writer_controls {
    int has_8bit_control;
    int has_sixel_scrolling;
    int has_sdm_glitch;
    int skip_dcs_envelope;
    int skip_header;
    int penetrate_multiplexer;
} sixel_writer_controls_t;

typedef struct sixel_writer_image_header {
    int parameter0;
    int parameter1;
    int parameter2;
    int parameter_count;
    int width;
    int height;
    int use_raster_attributes;
} sixel_writer_image_header_t;

/*
 * sixel_writer serializes terminal-framing bytes to the callback supplied by
 * the legacy public sixel_output_t wrapper.  The callback is invoked while the
 * writer lock is held, so a callback must not re-enter the same writer.
 */
/*
 * IDL responsibility:
 * - write framed terminal SIXEL bytes to callback-backed output
 */

/*
 * IDL forbidden state:
 * - image_pixels
 * - palette
 * - dither_policy
 * - encode_policy
 * - ormode
 * - transparent_policy
 * - gri_arg_limit
 * - body_run_state
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("write framed terminal SIXEL bytes to callback-backed output")]
 * [forbid_state("image_pixels", "palette", "dither_policy")]
 * [forbid_state("encode_policy", "ormode", "transparent_policy")]
 * [forbid_state("gri_arg_limit", "body_run_state")]
 * interface sixel_writer {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates]
 *     SIXELSTATUS init(in writer_init_request const *request);
 *     [mutates]
 *     SIXELSTATUS set_controls(in writer_controls const *controls);
 *     SIXELSTATUS get_controls(out writer_controls *controls);
 *     SIXELSTATUS begin_image(in writer_image_header const *header);
 *     SIXELSTATUS write(in char const *data, in int size);
 *     SIXELSTATUS end_image();
 * };
 */

typedef struct sixel_writer_vtbl {
    void (*ref)(sixel_writer_t *self);
    void (*unref)(sixel_writer_t *self);
    SIXELSTATUS (*init)(
        sixel_writer_t *self,
        sixel_writer_init_request_t const *request);
    SIXELSTATUS (*set_controls)(
        sixel_writer_t *self,
        sixel_writer_controls_t const *controls);
    SIXELSTATUS (*get_controls)(
        sixel_writer_t *self,
        sixel_writer_controls_t *controls);
    SIXELSTATUS (*begin_image)(
        sixel_writer_t *self,
        sixel_writer_image_header_t const *header);
    SIXELSTATUS (*write)(
        sixel_writer_t *self,
        char const *data,
        int size);
    SIXELSTATUS (*end_image)(sixel_writer_t *self);
} sixel_writer_vtbl_t;

struct sixel_writer_interface {
    sixel_writer_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("io/sixel-writer")]
 * coclass sixel_writer_component {
 *     [default] interface sixel_writer;
 * };
 */

typedef struct sixel_encoder_core_options {
    int has_gri_arg_limit;
    int palette_type;
    int encode_policy;
    int ormode;
    int transparent_policy;
    int transparent_offset_left;
    int transparent_offset_top;
    int pixelformat;
    int source_colorspace;
    int colorspace;
} sixel_encoder_core_options_t;

typedef struct sixel_encoder_core_encode_request {
    unsigned char *pixels;
    int width;
    int height;
    int depth;
    sixel_dither_t *dither;
    sixel_output_t *output;
} sixel_encoder_core_encode_request_t;

/*
 * encoder_core owns SIXEL body generation.  It receives image/quantization
 * state from the request and emits ordered body bytes through sixel_writer via
 * the legacy sixel_output_t wrapper.
 */
/*
 * IDL responsibility:
 * - encode image data into the SIXEL body stream
 */

/*
 * IDL forbidden state:
 * - callback_output
 * - dcs_envelope
 * - terminal_multiplexer
 * - image_file_output
 * - clipboard_output
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("encode image data into the SIXEL body stream")]
 * [forbid_state("callback_output", "dcs_envelope", "terminal_multiplexer", "image_file_output", "clipboard_output")]
 * interface encoder_core {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates]
 *     SIXELSTATUS set_options(in encoder_core_options const *options);
 *     SIXELSTATUS get_options(out encoder_core_options *options);
 *     SIXELSTATUS encode(in encoder_core_encode_request const *request);
 * };
 */

typedef struct sixel_encoder_core_vtbl {
    void (*ref)(sixel_encoder_core_t *self);
    void (*unref)(sixel_encoder_core_t *self);
    SIXELSTATUS (*set_options)(
        sixel_encoder_core_t *self,
        sixel_encoder_core_options_t const *options);
    SIXELSTATUS (*get_options)(
        sixel_encoder_core_t *self,
        sixel_encoder_core_options_t *options);
    SIXELSTATUS (*encode)(
        sixel_encoder_core_t *self,
        sixel_encoder_core_encode_request_t const *request);
} sixel_encoder_core_vtbl_t;

struct sixel_encoder_core_interface {
    sixel_encoder_core_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("codec/encoder-core")]
 * coclass encoder_core_component {
 *     [default] interface encoder_core;
 * };
 */

/*
 * IDL coclass:
 * [classid("codec/encoder-core.normal")]
 * coclass encoder_core_normal_component {
 *     [default] interface encoder_core;
 * };
 */

/*
 * IDL coclass:
 * [classid("codec/encoder-core.highcolor")]
 * coclass encoder_core_highcolor_component {
 *     [default] interface encoder_core;
 * };
 */

/*
 * IDL coclass:
 * [classid("codec/encoder-core.ormode")]
 * coclass encoder_core_ormode_component {
 *     [default] interface encoder_core;
 * };
 */

typedef struct sixel_factory_interface sixel_factory_t;

/*
 * IDL responsibility:
 * - create components by class id
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("create components by class id")]
 * [alias(sixel_factory_t)]
 * interface factory {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     SIXELSTATUS create(
 *         in char const *class_name,
 *         in allocator *allocator,
 *         out void **object);
 * };
 */

typedef struct sixel_factory_vtbl {
    void (*ref)(sixel_factory_t *self);
    void (*unref)(sixel_factory_t *self);
    SIXELSTATUS (*create)(
        sixel_factory_t *self,
        char const *class_name,
        sixel_allocator_t *allocator,
        void **object);
} sixel_factory_vtbl_t;

struct sixel_factory_interface {
    sixel_factory_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [serviceid("services/factory")]
 * coclass factory_component {
 *     [default] interface factory;
 * };
 */

/*
 * getservice("services/factory", &factory) returns the process-wide factory
 * service with interface-level ownership.  Release it with factory->vtbl->unref
 * when the caller is done with the service pointer.
 */
SIXELAPI SIXELSTATUS
sixel_components_getservice(char const *name,
    void **service);

typedef struct sixel_palette_interface sixel_palette_t;

typedef struct sixel_palette_entries_request {
    unsigned char const *entries;
    unsigned int colors;
    int depth;
} sixel_palette_entries_request_t;

typedef struct sixel_palette_float32_entries_request {
    float const *entries;
    unsigned int colors;
    int depth;
} sixel_palette_float32_entries_request_t;

typedef struct sixel_palette_generate_request {
    void const *data;
    unsigned int length;
    int pixelformat;
    unsigned int requested_colors;
    int method_for_largest;
    int method_for_rep;
    int quality_mode;
    int force_palette;
    int use_reversible;
    int quantize_model;
    int final_merge_mode;
    int lut_policy;
    int prefer_float32;
} sixel_palette_generate_request_t;

typedef struct sixel_palette_entries_view {
    unsigned char *entries;
    size_t entries_size;
    unsigned int entry_count;
    int depth;
} sixel_palette_entries_view_t;

typedef struct sixel_palette_float32_entries_view {
    float *entries;
    size_t entries_size;
    unsigned int entry_count;
    int depth;
} sixel_palette_float32_entries_view_t;

typedef struct sixel_palette_metadata {
    unsigned int entry_count;
    unsigned int requested_colors;
    unsigned int original_colors;
    int depth;
    int float_depth;
} sixel_palette_metadata_t;

/*
 * Ownership/lifetime:
 * - Factory create returns refcount=1 palette objects.
 * - Callers release with palette->vtbl->unref(palette).
 *
 * Encapsulation path:
 * - The palette object owns generated palette entries and metadata.
 * - Quantizer options are request-local generation inputs.
 * - Lookup policy caches belong to the dither/apply context.
 */
/*
 * IDL responsibility:
 * - own palette entries and quantization metadata only
 */

/*
 * IDL forbidden state:
 * - lookup_policy
 * - dither_policy
 * - input_pixels
 * - method_for_largest
 * - method_for_rep
 * - quality_mode
 * - force_palette
 * - use_reversible
 * - quantize_model
 * - final_merge_mode
 * - lut_policy
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("own palette entries and quantization metadata only")]
 * [forbid_state("lookup_policy", "dither_policy", "input_pixels", "method_for_largest", "method_for_rep", "quality_mode", "force_palette", "use_reversible", "quantize_model", "final_merge_mode", "lut_policy")]
 * [alias(sixel_palette_t)]
 * interface palette {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates, invalidates(entries_view, float32_entries_view)]
 *     SIXELSTATUS init_entries(in palette_entries_request const *request);
 *     [mutates, invalidates(float32_entries_view)]
 *     SIXELSTATUS init_entries_float32(
 *         in palette_float32_entries_request const *request);
 *     [mutates, invalidates(entries_view, float32_entries_view)]
 *     SIXELSTATUS generate(in palette_generate_request const *request);
 *     [const, borrows(entries_view)]
 *     SIXELSTATUS get_entries(out palette_entries_view *view);
 *     [const, borrows(float32_entries_view)]
 *     SIXELSTATUS get_entries_float32(out palette_float32_entries_view *view);
 *     [const]
 *     SIXELSTATUS get_metadata(out palette_metadata *metadata);
 * };
 */

typedef struct sixel_palette_vtbl {
    void (*ref)(sixel_palette_t *self);
    void (*unref)(sixel_palette_t *self);
    SIXELSTATUS (*init_entries)(
        sixel_palette_t *self,
        sixel_palette_entries_request_t const *request);
    SIXELSTATUS (*init_entries_float32)(
        sixel_palette_t *self,
        sixel_palette_float32_entries_request_t const *request);
    SIXELSTATUS (*generate)(
        sixel_palette_t *self,
        sixel_palette_generate_request_t const *request);
    SIXELSTATUS (*get_entries)(
        sixel_palette_t const *self,
        sixel_palette_entries_view_t *view);
    SIXELSTATUS (*get_entries_float32)(
        sixel_palette_t const *self,
        sixel_palette_float32_entries_view_t *view);
    SIXELSTATUS (*get_metadata)(
        sixel_palette_t const *self,
        sixel_palette_metadata_t *metadata);
} sixel_palette_vtbl_t;

struct sixel_palette_interface {
    sixel_palette_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("quant/palette")]
 * coclass palette_component {
 *     [default] interface palette;
 * };
 */

/*
 * Ownership/lifetime:
 * - Factory create returns refcount=1 policy objects.
 * - Callers release with policy->vtbl->unref(policy).
 *
 * Creation path:
 * - sixel_lookup_policy_select_name(select_request)
 * - services/factory -> create("lookup/...", allocator, &policy)
 * - factory resolves class ids via generated classid registry
 * - policy->prepare(request)
 *
 * Reuse path:
 * - Callers may pass a prepared policy object through
 *   request.reuse_policy/request.reuse_policy_slot.
 * - request.parallel_dither_active carries execution context so policies can
 *   disable non-thread-safe cache paths without relying on global state.
 * - request.shared_instance_enabled stores the effective shared-instance
 *   preference resolved by the caller (CLI override or environment default).
 * - Implementations may choose to ignore reuse hints.
 */
typedef struct sixel_lookup_policy_interface sixel_lookup_policy_interface_t;

typedef struct sixel_lookup_policy_select_request {
    unsigned char const *palette;
    int depth;
    int reqcolor;
    int optimize_lookup;
    int lut_policy;
    int pixelformat;
} sixel_lookup_policy_select_request_t;

typedef struct sixel_lookup_policy_prepare_request {
    unsigned char const *palette;
    float const *palette_float;
    int depth;
    int float_depth;
    int reqcolor;
    int pixelformat;
    int parallel_dither_active;
    int shared_instance_enabled;
    sixel_lookup_policy_interface_t *reuse_policy;
    sixel_lookup_policy_interface_t **reuse_policy_slot;
    sixel_allocator_t *allocator;
} sixel_lookup_policy_prepare_request_t;

typedef int sixel_lookup_policy_result_t;

/*
 * IDL responsibility:
 * - map pixels to palette indexes
 */

/*
 * IDL forbidden state:
 * - image_pixels
 * - output_pixels
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("map pixels to palette indexes")]
 * [forbid_state("image_pixels", "output_pixels")]
 * interface lookup_policy {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates]
 *     SIXELSTATUS prepare(in lookup_policy_prepare_request const *request);
 *     [const] lookup_policy_result map_pixel(
 *         in unsigned char const *pixel);
 * };
 */

typedef struct sixel_lookup_policy_vtbl {
    void (*ref)(sixel_lookup_policy_interface_t *self);
    void (*unref)(sixel_lookup_policy_interface_t *self);
    SIXELSTATUS (*prepare)(
        sixel_lookup_policy_interface_t *self,
        sixel_lookup_policy_prepare_request_t const *request);
    sixel_lookup_policy_result_t (*map_pixel)(
        sixel_lookup_policy_interface_t const *self,
        unsigned char const *pixel);
} sixel_lookup_policy_vtbl_t;

struct sixel_lookup_policy_interface {
    sixel_lookup_policy_vtbl_t const *vtbl;
};

/*
 * Ownership/lifetime:
 * - Factory create returns refcount=1 policy objects.
 * - Callers release with policy->vtbl->unref(policy).
 *
 * Creation path:
 * - sixel_dither_policy_select_name(select_request)
 * - services/factory -> create("dither/...", allocator, &policy)
 * - policy->prepare(request)
 */
typedef struct sixel_dither_policy_interface sixel_dither_policy_interface_t;

typedef struct sixel_dither_policy_select_request {
    int method_for_diffuse;
    int ncolors;
    int pixelformat;
} sixel_dither_policy_select_request_t;

typedef struct sixel_dither_policy_prepare_request {
    sixel_dither_t *dither;
    int depth;
    int method_for_scan;
    int pixelformat;
} sixel_dither_policy_prepare_request_t;

typedef struct sixel_dither_policy_apply_request {
    sixel_index_t *result;
    unsigned char *data;
    int width;
    int height;
    int band_origin;
    int output_start;
    int depth;
    unsigned char *palette;
    int method_for_scan;
    sixel_lookup_policy_interface_t *lookup_policy;
    sixel_dither_t *dither;
    int pixelformat;
} sixel_dither_policy_apply_request_t;

typedef int sixel_dither_policy_supports_parallel_result_t;

/*
 * IDL responsibility:
 * - apply dithering from pixels and lookup policy
 */

/*
 * IDL forbidden state:
 * - input_owner
 * - output_owner
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("apply dithering from pixels and lookup policy")]
 * [forbid_state("input_owner", "output_owner")]
 * interface dither_policy {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates]
 *     SIXELSTATUS prepare(in dither_policy_prepare_request const *request);
 *     SIXELSTATUS apply(in dither_policy_apply_request const *request);
 *     [const] dither_policy_supports_parallel_result supports_parallel_bands();
 * };
 */

typedef struct sixel_dither_policy_vtbl {
    void (*ref)(sixel_dither_policy_interface_t *self);
    void (*unref)(sixel_dither_policy_interface_t *self);
    SIXELSTATUS (*prepare)(
        sixel_dither_policy_interface_t *self,
        sixel_dither_policy_prepare_request_t const *request);
    SIXELSTATUS (*apply)(
        sixel_dither_policy_interface_t *self,
        sixel_dither_policy_apply_request_t const *request);
    sixel_dither_policy_supports_parallel_result_t
    (*supports_parallel_bands)(
        sixel_dither_policy_interface_t const *self);
} sixel_dither_policy_vtbl_t;

struct sixel_dither_policy_interface {
    sixel_dither_policy_vtbl_t const *vtbl;
};

typedef struct sixel_chunk_interface sixel_chunk_t;

typedef struct sixel_chunk_source_request {
    char const *filename;
    int finsecure;
    int const *cancel_flag;
} sixel_chunk_source_request_t;

typedef struct sixel_chunk_memory_request {
    unsigned char const *bytes;
    size_t size;
    char const *source_path;
} sixel_chunk_memory_request_t;

typedef struct sixel_chunk_bytes_view {
    unsigned char const *bytes;
    size_t size;
} sixel_chunk_bytes_view_t;

/*
 * Ownership/lifetime:
 * - Factory create returns refcount=1 chunk objects.
 * - Callers release with chunk->vtbl->unref(chunk).
 *
 * Encapsulation path:
 * - The chunk object owns loaded input bytes and optional source metadata.
 * - Loaders keep their own decode cursors; chunk bytes are read-only views.
 */
/*
 * IDL responsibility:
 * - own input bytes and source metadata only
 */

/*
 * IDL forbidden state:
 * - read_cursor
 * - decode_state
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("own input bytes and source metadata only")]
 * [forbid_state("read_cursor", "decode_state")]
 * interface chunk {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates, invalidates(bytes_view, source_path)]
 *     SIXELSTATUS init_source(in chunk_source_request const *request);
 *     [mutates, invalidates(bytes_view, source_path)]
 *     SIXELSTATUS init_memory(in chunk_memory_request const *request);
 *     [const, borrows(bytes_view)]
 *     SIXELSTATUS get_bytes(out chunk_bytes_view *view);
 *     [const, borrows(source_path)]
 *     char const *source_path();
 * };
 */

typedef struct sixel_chunk_vtbl {
    void (*ref)(sixel_chunk_t *self);
    void (*unref)(sixel_chunk_t *self);
    SIXELSTATUS (*init_source)(
        sixel_chunk_t *self,
        sixel_chunk_source_request_t const *request);
    SIXELSTATUS (*init_memory)(
        sixel_chunk_t *self,
        sixel_chunk_memory_request_t const *request);
    SIXELSTATUS (*get_bytes)(
        sixel_chunk_t const *self,
        sixel_chunk_bytes_view_t *view);
    char const *(*source_path)(sixel_chunk_t const *self);
} sixel_chunk_vtbl_t;

struct sixel_chunk_interface {
    sixel_chunk_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("image/chunk")]
 * coclass chunk_component {
 *     [default] interface chunk;
 * };
 */

typedef struct sixel_loader_component_interface
    sixel_loader_component_interface_t;

/*
 * IDL responsibility:
 * - decode one chunk through one loader backend
 */

/*
 * IDL forbidden state:
 * - loader_chain
 * - global_decode_cursor
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("decode one chunk through one loader backend")]
 * [forbid_state("loader_chain", "global_decode_cursor")]
 * interface loader_component {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates]
 *     SIXELSTATUS setopt(in int option, in void const *value);
 *     SIXELSTATUS load(
 *         in chunk const *chunk,
 *         in sixel_load_image_function fn_load,
 *         in void *context);
 *     [const] char const *name();
 *     int predicate(in chunk const *chunk);
 * };
 */

typedef struct sixel_loader_component_vtbl {
    void (*ref)(sixel_loader_component_interface_t *self);
    void (*unref)(sixel_loader_component_interface_t *self);
    SIXELSTATUS (*setopt)(
        sixel_loader_component_interface_t *self,
        int option,
        void const *value);
    SIXELSTATUS (*load)(
        sixel_loader_component_interface_t *self,
        sixel_chunk_t const *chunk,
        sixel_load_image_function fn_load,
        void *context);
    char const *(*name)(sixel_loader_component_interface_t const *self);
    int (*predicate)(
        sixel_loader_component_interface_t *self,
        sixel_chunk_t const *chunk);
} sixel_loader_component_vtbl_t;

struct sixel_loader_component_interface {
    sixel_loader_component_vtbl_t const *vtbl;
};

typedef sixel_loader_component_interface_t sixel_loader_component_t;

typedef sixel_loader_component_vtbl_t sixel_loader_vtbl_t;

typedef struct sixel_loader_manager_interface sixel_loader_manager_t;

typedef struct sixel_loader_suboptions {
    int wic_ico_minsize;
    int libjpeg_enable_cms;
    int libjpeg_cms_engine;
    int libjpeg_enable_orientation;
    int libpng_enable_cms;
    int libpng_cms_engine;
    int libpng_enable_orientation;
    int libwebp_enable_cms;
    int libwebp_cms_engine;
    int libwebp_enable_orientation;
    int coregraphics_enable_orientation;
    int libtiff_enable_cms;
    int libtiff_cms_engine;
    int builtin_enable_cms;
    int builtin_cms_engine;
    int builtin_enable_orientation;
    int builtin_bmp_info40_mode;
} sixel_loader_suboptions_t;

typedef struct sixel_loader_manager_build_request {
    struct sixel_option_argument_list_resolution const *resolution;
    int skip_predicate_gate;
    int require_static;
    int use_palette;
    int reqcolors;
    unsigned char const *bgcolor;
    int has_bgcolor;
    int bgcolor_source;
    int loop_control;
    int has_start_frame_no;
    int start_frame_no;
    sixel_loader_suboptions_t const *suboptions;
    sixel_timeline_logger_t *timeline_logger;
    int *timeline_job_seq;
    sixel_loader_t *timeline_loader;
} sixel_loader_manager_build_request_t;

/*
 * IDL responsibility:
 * - build loader chains and select loaders for chunks
 */

/*
 * IDL forbidden state:
 * - chunk_bytes
 * - pixel_storage
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("build loader chains and select loaders for chunks")]
 * [forbid_state("chunk_bytes", "pixel_storage")]
 * interface loader_manager {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates, invalidates(loader_chain, selected_loader)]
 *     SIXELSTATUS build_chain(in loader_manager_build_request const *request);
 *     [borrows(selected_loader)]
 *     SIXELSTATUS load(
 *         in chunk const *chunk,
 *         out loader_component **selected_loader,
 *         in sixel_load_image_function fn_load,
 *         in void *load_context);
 * };
 */

typedef struct sixel_loader_manager_vtbl {
    void (*ref)(sixel_loader_manager_t *self);
    void (*unref)(sixel_loader_manager_t *self);
    SIXELSTATUS (*build_chain)(
        sixel_loader_manager_t *self,
        sixel_loader_manager_build_request_t const *request);
    SIXELSTATUS (*load)(
        sixel_loader_manager_t *self,
        sixel_chunk_t const *chunk,
        sixel_loader_component_interface_t **selected_loader,
        sixel_load_image_function fn_load,
        void *load_context);
} sixel_loader_manager_vtbl_t;

struct sixel_loader_manager_interface {
    sixel_loader_manager_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("loader/manager")]
 * coclass loader_manager_component {
 *     [default] interface loader_manager;
 * };
 */

/*
 * Ownership/lifetime:
 * - Existing public sixel_frame_new() returns refcount=1 frame objects.
 * - init_pixels() takes ownership of request->pixels and request->palette,
 *   matching sixel_frame_init().
 * - set_transparency() takes ownership of request->transparent_mask.
 *
 * Encapsulation path:
 * - This header exposes only the object contract and request/view DTOs.
 * - src/frame-private.h remains a temporary storage owner while loader-side
 *   direct-field callers migrate toward this interface.
 * - src/frame.c owns frame operations that need concrete storage access.
 */
typedef struct sixel_frame_interface sixel_frame_interface_t;

typedef enum sixel_frame_pixels_kind {
    SIXEL_FRAME_PIXELS_U8 = 0,
    SIXEL_FRAME_PIXELS_FLOAT32 = 1
} sixel_frame_pixels_kind_t;

typedef struct sixel_frame_pixels_request {
    void *pixels;
    unsigned char *palette;
    int width;
    int height;
    int pixelformat;
    int colorspace; /* negative means infer from pixelformat */
    int ncolors;
    sixel_frame_pixels_kind_t kind;
} sixel_frame_pixels_request_t;

typedef struct sixel_frame_pixels_view {
    unsigned char *pixels;
    float *pixels_float32;
    unsigned char *palette;
    int width;
    int height;
    int pixelformat;
    int colorspace;
    int ncolors;
} sixel_frame_pixels_view_t;

typedef struct sixel_frame_timeline {
    int delay;
    int frame_no;
    int loop_count;
    int multiframe;
    int handoff_shareable;
} sixel_frame_timeline_t;

typedef struct sixel_frame_transparency {
    int transparent;
    int alpha_zero_is_transparent;
    unsigned char *transparent_mask;
    size_t transparent_mask_size;
} sixel_frame_transparency_t;

/*
 * IDL responsibility:
 * - own pixel storage and per-frame metadata
 */

/*
 * IDL forbidden state:
 * - lookup_policy
 * - dither_policy
 * - decode_state
 */

/*
 * IDL contract:
 * [component, refcounted]
 * [responsibility("own pixel storage and per-frame metadata")]
 * [forbid_state("lookup_policy", "dither_policy", "decode_state")]
 * interface frame {
 *     [lifetime(retained)]
 *     void ref();
 *     [lifetime(release)]
 *     void unref();
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS init_pixels(in frame_pixels_request const *request);
 *     [borrows(pixels_view)]
 *     SIXELSTATUS get_pixels(out frame_pixels_view *view);
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS set_pixelformat(in int pixelformat);
 *     SIXELSTATUS get_timeline(out frame_timeline *timeline);
 *     [mutates]
 *     SIXELSTATUS set_timeline(in frame_timeline const *timeline);
 *     SIXELSTATUS get_transparency(out frame_transparency *transparency);
 *     [mutates]
 *     SIXELSTATUS set_transparency(in frame_transparency const *transparency);
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS resize(
 *         in int width,
 *         in int height,
 *         in int method_for_resampling);
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS resize_float32(
 *         in int width,
 *         in int height,
 *         in int method_for_resampling);
 *     [mutates, invalidates(pixels_view)]
 *     SIXELSTATUS clip(in int x, in int y, in int width, in int height);
 *     SIXELSTATUS measure_storage(out size_t *storage_bytes);
 *     SIXELSTATUS clone(
 *         in allocator *allocator,
 *         out frame **frame_out);
 * };
 */

typedef struct sixel_frame_vtbl {
    void (*ref)(sixel_frame_interface_t *self);
    void (*unref)(sixel_frame_interface_t *self);
    SIXELSTATUS (*init_pixels)(
        sixel_frame_interface_t *self,
        sixel_frame_pixels_request_t const *request);
    SIXELSTATUS (*get_pixels)(
        sixel_frame_interface_t *self,
        sixel_frame_pixels_view_t *view);
    SIXELSTATUS (*set_pixelformat)(
        sixel_frame_interface_t *self,
        int pixelformat);
    SIXELSTATUS (*get_timeline)(
        sixel_frame_interface_t *self,
        sixel_frame_timeline_t *timeline);
    SIXELSTATUS (*set_timeline)(
        sixel_frame_interface_t *self,
        sixel_frame_timeline_t const *timeline);
    SIXELSTATUS (*get_transparency)(
        sixel_frame_interface_t *self,
        sixel_frame_transparency_t *transparency);
    SIXELSTATUS (*set_transparency)(
        sixel_frame_interface_t *self,
        sixel_frame_transparency_t const *transparency);
    SIXELSTATUS (*resize)(
        sixel_frame_interface_t *self,
        int width,
        int height,
        int method_for_resampling);
    SIXELSTATUS (*resize_float32)(
        sixel_frame_interface_t *self,
        int width,
        int height,
        int method_for_resampling);
    SIXELSTATUS (*clip)(
        sixel_frame_interface_t *self,
        int x,
        int y,
        int width,
        int height);
    SIXELSTATUS (*measure_storage)(
        sixel_frame_interface_t *self,
        size_t *storage_bytes);
    SIXELSTATUS (*clone)(
        sixel_frame_interface_t *self,
        sixel_allocator_t *allocator,
        sixel_frame_interface_t **frame_out);
} sixel_frame_vtbl_t;

struct sixel_frame_interface {
    sixel_frame_vtbl_t const *vtbl;
};

/*
 * IDL coclass:
 * [classid("image/frame")]
 * coclass frame_component {
 *     [default] interface frame;
 * };
 */

static inline sixel_frame_interface_t *
sixel_frame_as_interface(sixel_frame_t const *frame)
{
    return (sixel_frame_interface_t *)frame;
}

#ifdef __cplusplus
}
#endif

#endif /* LIBSIXEL_6CELLS_H */

/* emacs Local Variables:      */
/* emacs mode: c               */
/* emacs tab-width: 4          */
/* emacs indent-tabs-mode: nil */
/* emacs c-basic-offset: 4     */
/* emacs End:                  */
/* vim: set expandtab ts=4 sts=4 sw=4 : */
/* EOF */
