#!/bin/sh
# Generate amalgamated sixel.c that stitches together all primary C sources.
# Usage: gen-amalgamation.sh OUTPUT [SOURCE_ROOT] [BUILD_ROOT]
# SOURCE_ROOT defaults to the repository root relative to this script.
# BUILD_ROOT defaults to SOURCE_ROOT. All comment strings must stay in English.

set -eu

if [ "$#" -lt 1 ] || [ "$#" -gt 3 ]; then
    echo "Usage: $0 OUTPUT [SOURCE_ROOT] [BUILD_ROOT]" >&2
    exit 1
fi

output=$1
script_dir=$(cd "$(dirname "$0")" && pwd)
default_root=$(cd "${script_dir}/.." && pwd)
src_root=${2:-${default_root}}
build_root=${3:-${src_root}}

mkdir -p "$(dirname "${output}")"

relpath() {
    python3 - "$@" <<'PY'
import os
import sys
base = sys.argv[1]
target = sys.argv[2]
print(os.path.relpath(target, base))
PY
}

out_dir=$(cd "$(dirname "${output}")" && pwd)
rel_src=$(relpath "${out_dir}" "${src_root}")
rel_build=$(relpath "${out_dir}" "${build_root}")

cat >"${output}" <<EOF_HEADER
/*
 * SPDX-License-Identifier: MIT
 *
 * This file is generated by tools/gen-amalgamation.sh.
 * Do not edit manually. Enable the amalgamation option to rebuild it.
 */

#if !defined(_GNU_SOURCE)
#define _GNU_SOURCE 1
#endif
#if !defined(_DARWIN_C_SOURCE)
#define _DARWIN_C_SOURCE 1
#endif
#if !defined(_POSIX_C_SOURCE)
#define _POSIX_C_SOURCE 200809L
#endif
#if !defined(_XOPEN_SOURCE)
#define _XOPEN_SOURCE 700
#endif

#define SIXEL_AMALGAMATION 1
#include "${rel_build}/config.h"

/* Core pipeline and dither helpers */
#include "${rel_src}/src/output.c"
#include "${rel_src}/src/fromsixel.c"
#include "${rel_src}/src/tosixel.c"
#include "${rel_src}/src/timer.c"
#include "${rel_src}/src/assessment.c"
#include "${rel_src}/src/sleep.c"
#include "${rel_src}/src/lookup-common.c"
#include "${rel_src}/src/lookup-8bit.c"
#include "${rel_src}/src/lookup-float32.c"
#include "${rel_src}/src/lookup-vpte-8bit.c"
#include "${rel_src}/src/lookup-vpte-float32.c"
#include "${rel_src}/src/palette-heckbert.c"
#include "${rel_src}/src/palette-common-merge.c"
#include "${rel_src}/src/palette-common-snap.c"
#include "${rel_src}/src/palette-kmeans.c"
#include "${rel_src}/src/palette.c"
#include "${rel_src}/src/dither.c"
#include "${rel_src}/src/dither-common-pipeline.c"
#include "${rel_src}/src/dither-positional-8bit.c"
#include "${rel_src}/src/dither-positional-float32.c"
#include "${rel_src}/src/dither-fixed-8bit.c"
#include "${rel_src}/src/dither-fixed-float32.c"
#include "${rel_src}/src/dither-varcoeff-8bit.c"
#include "${rel_src}/src/dither-varcoeff-float32.c"

/* Support utilities and platform helpers */
#include "${rel_src}/src/logger.c"
#include "${rel_src}/src/colorspace.c"
#include "${rel_src}/src/frame.c"
#include "${rel_src}/src/cpu.c"
#include "${rel_src}/src/pixelformat.c"
#include "${rel_src}/src/scale.c"
#include "${rel_src}/src/chunk.c"
#include "${rel_src}/src/loader.c"
#include "${rel_src}/src/loader-gdk-pixbuf2.c"
#include "${rel_src}/src/loader-gnome-thumbnailer.c"
#include "${rel_src}/src/loader-coregraphics.c"
#include "${rel_src}/src/loader-quicklook.c"
#include "${rel_src}/src/loader-wic.c"
#include "${rel_src}/src/loader-gd.c"
#include "${rel_src}/src/loader-libpng.c"
#include "${rel_src}/src/loader-libjpeg.c"
#include "${rel_src}/src/loader-builtin.c"
#include "${rel_src}/src/loader-common.c"
#include "${rel_src}/src/loader-registry.c"
#include "${rel_src}/src/frompnm.c"
#include "${rel_src}/src/fromgif.c"
#include "${rel_src}/src/clipboard.c"
#include "${rel_src}/src/encoder.c"
#include "${rel_src}/src/decoder.c"
#include "${rel_src}/src/decoder-parallel.c"
#include "${rel_src}/src/options.c"
#include "${rel_src}/src/writer.c"
#include "${rel_src}/src/stb_image_write.c"
#include "${rel_src}/src/status.c"
#include "${rel_src}/src/compat_stub.c"
#include "${rel_src}/src/malloc_stub.c"
#include "${rel_src}/src/allocator.c"
#include "${rel_src}/src/tty.c"
#include "${rel_src}/src/threading.c"

#if SIXEL_ENABLE_THREADS
#include "${rel_src}/src/threadpool.c"
#endif

#if HAVE_QUICKLOOK_THUMBNAILING && defined(__OBJC__)
#include "${rel_src}/src/quicklook_thumbnailing.m"
#endif

#if HAVE_CLIPBOARD_MACOS && defined(__OBJC__)
#include "${rel_src}/src/clipboard_macos.m"
#endif
EOF_HEADER
printf '\n' >>"${output}"
