#!/usr/bin/awk -f
# Generate classid-dither.gperf from dither policy class-id annotations.

BEGIN {
    header_count = 0
    entry_count = 0
    pending_classid = ""
    has_error = 0
}

function report_error(message) {
    printf("%s:%d: %s\n", FILENAME, FNR, message) > "/dev/stderr"
    has_error = 1
}

FNR == 1 {
    header_name = FILENAME
    sub(/^.*\//, "", header_name)
    if (!(header_name in header_seen)) {
        header_seen[header_name] = 1
        ++header_count
        headers[header_count] = header_name
    }
}

{
    if ($0 ~ /^[ \t]*\/\*[ \t]*@classid[ \t]+/) {
        classid_line = $0
        sub(/^[ \t]*\/\*[ \t]*@classid[ \t]+/, "", classid_line)
        sub(/[ \t]*\*\/[ \t]*$/, "", classid_line)
        if (classid_line !~ /^[A-Za-z0-9_.\/-]+$/) {
            report_error("invalid @classid token: " classid_line)
            next
        }
        if (pending_classid != "") {
            report_error("missing constructor after @classid " pending_classid)
        }
        pending_classid = classid_line
        next
    }

    if (pending_classid != "" &&
            match($0, /sixel_dither_policy_create_[A-Za-z0-9_]+/)) {
        constructor_name = substr($0, RSTART, RLENGTH)
        if (pending_classid in classid_to_constructor) {
            report_error("duplicate @classid " pending_classid)
            next
        }
        classid_to_constructor[pending_classid] = constructor_name
        ++entry_count
        classids[entry_count] = pending_classid
        constructors[entry_count] = constructor_name
        pending_classid = ""
    }
}

END {
    if (pending_classid != "") {
        printf("error: missing constructor after @classid %s\n",
               pending_classid) > "/dev/stderr"
        has_error = 1
    }

    if (entry_count == 0) {
        printf("error: no @classid annotations found\n") > "/dev/stderr"
        has_error = 1
    }

    if (has_error != 0) {
        exit 1
    }

    print "/* auto-generated by tools/gen_dither_classid_gperf.awk; do not edit */"
    print "%language=ANSI-C"
    print "%readonly-tables"
    print "%global-table"
    print "%struct-type"
    print "%{"
    print "#if defined(HAVE_STRING_H) && HAVE_STRING_H"
    print "#include <string.h>"
    print "#endif"
    for (i = 1; i <= header_count; ++i) {
        printf("#include \"%s\"\n", headers[i])
    }
    print ""
    print "typedef SIXELSTATUS (*sixel_dither_policy_create_fn)("
    print "    sixel_dither_policy_interface_t **policy);"
    print "%}"
    print "struct sixel_dither_policy_classid_entry {"
    print "    char const *name;"
    print "    sixel_dither_policy_create_fn create;"
    print "};"
    print "%%"
    for (i = 1; i <= entry_count; ++i) {
        printf("%s, %s\n", classids[i], constructors[i])
    }
    print "%%"
}
