#!/usr/bin/awk -f
# Generate classid-service.gperf from service-id annotations.

BEGIN {
    header_count = 0
    entry_count = 0
    pending_serviceid = ""
    pending_condition = ""
    has_error = 0
}

function report_error(message) {
    printf("%s:%d: %s\n", FILENAME, FNR, message) > "/dev/stderr"
    has_error = 1
}

function trim(text) {
    gsub(/^[ \t]+/, "", text)
    gsub(/[ \t]+$/, "", text)
    return text
}

FNR == 1 {
    header_name = FILENAME
    sub(/^.*\//, "", header_name)
    if (!(header_name in header_seen)) {
        header_seen[header_name] = 1
        ++header_count
        headers[header_count] = header_name
    }
}

{
    if ($0 ~ /^[ \t]*\/\*[ \t]*@serviceid[ \t]+/) {
        serviceid_line = $0
        serviceid = ""
        condition = "1"

        sub(/^[ \t]*\/\*[ \t]*@serviceid[ \t]+/, "", serviceid_line)
        sub(/[ \t]*\*\/[ \t]*$/, "", serviceid_line)
        serviceid_line = trim(serviceid_line)

        if (serviceid_line ~ /[ \t]+if[ \t]+/) {
            split(serviceid_line, parts, /[ \t]+if[ \t]+/)
            serviceid = trim(parts[1])
            condition = trim(parts[2])
        } else {
            serviceid = serviceid_line
        }

        if (serviceid !~ /^[A-Za-z0-9_.\/-]+$/) {
            report_error("invalid @serviceid token: " serviceid)
            next
        }
        if (condition == "") {
            report_error("empty @serviceid condition: " serviceid)
            next
        }
        if (condition !~ /^[A-Za-z0-9_()!&| \t]+$/) {
            report_error("invalid @serviceid condition: " condition)
            next
        }

        if (pending_serviceid != "") {
            report_error("missing getter after @serviceid " pending_serviceid)
        }
        pending_serviceid = serviceid
        pending_condition = condition
        next
    }

    if (pending_serviceid != "" &&
            match($0, /sixel_[A-Za-z0-9_]+_get_default/)) {
        getter_name = substr($0, RSTART, RLENGTH)
        if (pending_serviceid in serviceid_to_getter) {
            report_error("duplicate @serviceid " pending_serviceid)
            next
        }
        serviceid_to_getter[pending_serviceid] = getter_name
        ++entry_count
        serviceids[entry_count] = pending_serviceid
        getters[entry_count] = getter_name
        conditions[entry_count] = pending_condition
        pending_serviceid = ""
        pending_condition = ""
    }
}

END {
    if (pending_serviceid != "") {
        printf("error: missing getter after @serviceid %s\n",
               pending_serviceid) > "/dev/stderr"
        has_error = 1
    }

    if (entry_count == 0) {
        printf("error: no @serviceid annotations found\n") > "/dev/stderr"
        has_error = 1
    }

    if (has_error != 0) {
        exit 1
    }

    print "/* auto-generated by tools/gen_serviceid_gperf.awk; do not edit */"
    print "%language=ANSI-C"
    print "%readonly-tables"
    print "%global-table"
    print "%struct-type"
    print "%{"
    print "#if defined(HAVE_STRING_H) && HAVE_STRING_H"
    print "#include <string.h>"
    print "#endif"
    for (i = 1; i <= header_count; ++i) {
        printf("#include \"%s\"\n", headers[i])
    }
    print ""
    print "typedef SIXELSTATUS (*sixel_components_service_get_fn)("
    print "    void **service);"
    print ""
    for (i = 1; i <= entry_count; ++i) {
        macro_name = "SIXEL_COMPONENTS_SERVICEID_GET_" i
        printf("#if %s\n", conditions[i])
        printf("# define %s %s\n", macro_name, getters[i])
        print "#else"
        printf("# define %s 0\n", macro_name)
        print "#endif"
    }
    print "%}"
    print "struct sixel_components_serviceid_entry {"
    print "    char const *name;"
    print "    sixel_components_service_get_fn get_default;"
    print "};"
    print "%%"
    for (i = 1; i <= entry_count; ++i) {
        macro_name = "SIXEL_COMPONENTS_SERVICEID_GET_" i
        printf("%s, %s\n", serviceids[i], macro_name)
    }
    print "%%"
}
