#!/usr/bin/awk -f
# Generate classid-loader.gperf from loader class-id annotations.

BEGIN {
    header_count = 0
    entry_count = 0
    pending_classid = ""
    pending_condition = ""
    has_error = 0
}

function report_error(message) {
    printf("%s:%d: %s\n", FILENAME, FNR, message) > "/dev/stderr"
    has_error = 1
}

function trim(text) {
    gsub(/^[ \t]+/, "", text)
    gsub(/[ \t]+$/, "", text)
    return text
}

FNR == 1 {
    header_name = FILENAME
    sub(/^.*\//, "", header_name)
    if (!(header_name in header_seen)) {
        header_seen[header_name] = 1
        ++header_count
        headers[header_count] = header_name
    }
}

{
    if ($0 ~ /^[ \t]*\/\*[ \t]*@classid[ \t]+/) {
        classid_line = $0
        classid = ""
        condition = "1"
        token = ""

        sub(/^[ \t]*\/\*[ \t]*@classid[ \t]+/, "", classid_line)
        sub(/[ \t]*\*\/[ \t]*$/, "", classid_line)
        classid_line = trim(classid_line)

        if (classid_line ~ /[ \t]+if[ \t]+/) {
            split(classid_line, parts, /[ \t]+if[ \t]+/)
            classid = trim(parts[1])
            condition = trim(parts[2])
        } else {
            classid = classid_line
        }

        if (classid !~ /^[A-Za-z0-9_.\/-]+$/) {
            report_error("invalid @classid token: " classid)
            next
        }
        if (condition == "") {
            report_error("empty @classid condition: " classid)
            next
        }
        if (condition !~ /^[A-Za-z0-9_()!&| \t]+$/) {
            report_error("invalid @classid condition: " condition)
            next
        }

        if (pending_classid != "") {
            report_error("missing constructor after @classid " pending_classid)
        }
        pending_classid = classid
        pending_condition = condition
        next
    }

    if (pending_classid != "" &&
            match($0, /sixel_loader_[A-Za-z0-9_]+_new/)) {
        constructor_name = substr($0, RSTART, RLENGTH)
        if (pending_classid in classid_to_constructor) {
            report_error("duplicate @classid " pending_classid)
            next
        }
        classid_to_constructor[pending_classid] = constructor_name
        ++entry_count
        classids[entry_count] = pending_classid
        constructors[entry_count] = constructor_name
        conditions[entry_count] = pending_condition
        pending_classid = ""
        pending_condition = ""
    }
}

END {
    if (pending_classid != "") {
        printf("error: missing constructor after @classid %s\n",
               pending_classid) > "/dev/stderr"
        has_error = 1
    }

    if (entry_count == 0) {
        printf("error: no @classid annotations found\n") > "/dev/stderr"
        has_error = 1
    }

    if (has_error != 0) {
        exit 1
    }

    print "/* auto-generated by tools/gen_loader_classid_gperf.awk; do not edit */"
    print "%language=ANSI-C"
    print "%readonly-tables"
    print "%global-table"
    print "%struct-type"
    print "%{"
    print "#if defined(HAVE_STRING_H) && HAVE_STRING_H"
    print "#include <string.h>"
    print "#endif"
    for (i = 1; i <= header_count; ++i) {
        printf("#include \"%s\"\n", headers[i])
    }
    print ""
    print "typedef SIXELSTATUS (*sixel_loader_component_new_fn)("
    print "    sixel_allocator_t *allocator,"
    print "    sixel_loader_component_t **ppcomponent);"
    print ""
    for (i = 1; i <= entry_count; ++i) {
        macro_name = "SIXEL_LOADER_COMPONENT_CLASSID_CREATE_" i
        printf("#if %s\n", conditions[i])
        printf("# define %s %s\n", macro_name, constructors[i])
        print "#else"
        printf("# define %s 0\n", macro_name)
        print "#endif"
    }
    print "%}"
    print "struct sixel_loader_component_classid_entry {"
    print "    char const *name;"
    print "    sixel_loader_component_new_fn create;"
    print "};"
    print "%%"
    for (i = 1; i <= entry_count; ++i) {
        macro_name = "SIXEL_LOADER_COMPONENT_CLASSID_CREATE_" i
        printf("%s, %s\n", classids[i], macro_name)
    }
    print "%%"
}
