name: libsixel CI (build & test)

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            compiler: gcc
            sys: MINGW64
          - os: windows-latest
            compiler: gcc
            sys: UCRT64
          - os: windows-latest
            compiler: clang
            sys: CLANG64
          - os: windows-latest
            compiler: cl
            sys: MSYS

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSVC developer env (vcvars)
      if: ${{ matrix.os == 'windows-latest' && matrix.compiler == 'cl' }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Setup MSYS2 (Windows, not MSVC)
      if: runner.os == 'Windows' && matrix.compiler != 'cl'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          make
          zip
        pacboy: >-
          cc:p

    - name: Setup MSYS2 (Windows, MSVC)
      if: runner.os == 'Windows' && matrix.compiler == 'cl'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          make
          zip

    - name: Configure and build (non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        ./configure \
            --without-png \
            --without-jpeg \
            --without-libcurl \
            --without-bashcompletiondir \
            --without-zshcompletiondir \
            --disable-python \
            --disable-dependency-tracking
        make

    - name: Configure and build (Windows, not MSVC)
      if: ${{ runner.os == 'Windows' && matrix.compiler != 'cl' }}
      shell: msys2 {0}
      run: |
        ./configure CC=${{ matrix.compiler }} \
            --without-png \
            --without-jpeg \
            --without-libcurl \
            --without-bashcompletiondir \
            --without-zshcompletiondir \
            --disable-python \
            --disable-dependency-tracking
        make

    - name: Configure and build (Windows, MSVC)
      if: ${{ runner.os == 'Windows' && matrix.compiler == 'cl' }}
      shell: msys2 {0}
      run: |
        VCVARS="$(cygpath -w "$VSINSTALLDIR")\\VC\\Auxiliary\\Build\\vcvarsall.bat"
        cmd //c call "${VCVARS}" x64 \>nul \&\& set
        eval $(
            cmd //c call "${VCVARS}" x64 \>nul \&\& set |
            grep -i '^\(PATH\|INCLUDE\|LIB\|LIBPATH\)'  |
            while IFS== read -r key val; do
                case "$key" in PATH|Path)
                    echo export PATH=\"$(echo "$val" | tr \; \\n | while read -r p; do cygpath "$p"; done | grep ^/ | tr \\n :)\"\;
                    ;;
                *)
                    echo export "$key"=\""$val"\"\;
                    ;;
                esac;
            done
        )

        chmod +x "$(pwd)/tools/ar-msvc.sh"

        ./configure CC=cl LD=link AR="$(pwd)/tools/ar-msvc.sh" ARFLAGS= NM="dumpbin -symbols" STRIP=: RANLIB=: \
            --host=x86_64-pc-windows-msvc \
            --without-png \
            --without-jpeg \
            --without-libcurl \
            --without-bashcompletiondir \
            --without-zshcompletiondir \
            --disable-python \
            --disable-dependency-tracking
        make

    - name: Run tests (non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      run: make check

    - name: Run tests (Windows, not MSVC)
      if: runner.os == 'Windows' && matrix.compiler != 'cl'
      shell: msys2 {0}
      run: make check

    - name: Run tests (Windows, MSVC)
      if: runner.os == 'Windows' && matrix.compiler == 'cl'
      shell: msys2 {0}
      run: |
        VCVARS="$(cygpath -w "$VSINSTALLDIR")\\VC\\Auxiliary\\Build\\vcvarsall.bat"
        cmd //c call "${VCVARS}" x64 \>nul \&\& set
        eval $(
            cmd //c call "${VCVARS}" x64 \>nul \&\& set |
            grep -i '^\(PATH\|INCLUDE\|LIB\|LIBPATH\)'  |
            while IFS== read -r key val; do
                case "$key" in PATH|Path)
                    echo export PATH=\"$(echo "$val" | tr \; \\n | while read -r p; do cygpath "$p"; done | grep ^/ | tr \\n :)\"\;
                    ;;
                *)
                    echo export "$key"=\""$val"\"\;
                    ;;
                esac;
            done
        )
        make check V=1


# emacs Local Variables:
# emacs mode: c
# emacs tab-width: 4
# emacs indent-tabs-mode: nil
# emacs c-basic-offset: 4
# emacs End:
# vim: set ft=awk et ts=4 sw=0 sts=-1 fdm=marker fdl=0:
